Repository PowerGridModel/power-grid-model, pull requests merged in 2023-07, with the labels that each got.

#289 Feature/short circuit calculation python api
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c.h
  src/power_grid_model/__init__.py
  src/power_grid_model/core/data_handling.py
  src/power_grid_model/core/power_grid_model.py
  src/power_grid_model/enum.py
  tests/cpp_unit_tests/test_main_model.cpp
  tests/data/short_circuit/single_phase_to_ground_a/input.json
  tests/data/short_circuit/single_phase_to_ground_a/params.json
  tests/data/short_circuit/single_phase_to_ground_b/input.json
  tests/data/short_circuit/single_phase_to_ground_b/params.json
  tests/data/short_circuit/single_phase_to_ground_b/sc_output_batch.json
  tests/data/short_circuit/single_phase_to_ground_c/input.json
  tests/data/short_circuit/single_phase_to_ground_c/params.json
  tests/data/short_circuit/single_phase_to_ground_c/sc_output_batch.json
  tests/data/short_circuit/three_phase_abc/input.json
  tests/data/short_circuit/three_phase_abc/params.json
  tests/data/short_circuit/two_phase_ab/input.json
  tests/data/short_circuit/two_phase_ab/params.json
  tests/data/short_circuit/two_phase_ab/sc_output_batch.json
  tests/data/short_circuit/two_phase_ac/input.json
  tests/data/short_circuit/two_phase_ac/params.json
  tests/data/short_circuit/two_phase_ac/sc_output_batch.json
  tests/data/short_circuit/two_phase_bc/input.json
  tests/data/short_circuit/two_phase_bc/params.json
  tests/data/short_circuit/two_phase_to_ground_ab/input.json
  tests/data/short_circuit/two_phase_to_ground_ab/params.json
  tests/data/short_circuit/two_phase_to_ground_ab/sc_output_batch.json
  tests/data/short_circuit/two_phase_to_ground_ac/input.json
  tests/data/short_circuit/two_phase_to_ground_ac/params.json
  tests/data/short_circuit/two_phase_to_ground_ac/sc_output_batch.json
  tests/data/short_circuit/two_phase_to_ground_bc/input.json
  tests/data/short_circuit/two_phase_to_ground_bc/params.json
  tests/unit/test_0Z_model_validation.py
  tests/unit/test_power_grid_model.py
  tests/unit/utils.py
Labels: feature

#290 Feature/improve fault enum order
  docs/user_manual/components.md
  power_grid_model_c/power_grid_model/include/power_grid_model/enum.hpp
  src/power_grid_model/enum.py
  tests/data/short_circuit/single_phase_to_ground_a/input.json
  tests/data/short_circuit/single_phase_to_ground_b/input.json
  tests/data/short_circuit/single_phase_to_ground_c/input.json
  tests/data/short_circuit/three_phase_abc/input.json
  tests/data/short_circuit/two_phase_ab/input.json
  tests/data/short_circuit/two_phase_ac/input.json
  tests/data/short_circuit/two_phase_bc/input.json
  tests/data/short_circuit/two_phase_to_ground_ab/input.json
  tests/data/short_circuit/two_phase_to_ground_ac/input.json
  tests/data/short_circuit/two_phase_to_ground_bc/input.json
Labels: improvement

#294 Feature/separate nan default enum values
  docs/advanced_documentation/native-data-interface.md
  docs/user_manual/components.md
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/enum.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/exception.hpp
  src/power_grid_model/enum.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/validation.py
  tests/cpp_unit_tests/test_fault.cpp
  tests/unit/validation/test_rules.py
  tests/unit/validation/test_validation_functions.py
Labels: improvement

#292 Feature/short circuit input validation
  docs/advanced_documentation/native-data-interface.md
  docs/user_manual/calculations.md
  docs/user_manual/components.md
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/enum.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/exception.hpp
  src/power_grid_model/enum.py
  src/power_grid_model/validation/errors.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/validation.py
  tests/cpp_unit_tests/test_fault.cpp
  tests/unit/validation/test_input_validation.py
  tests/unit/validation/test_rules.py
  tests/unit/validation/test_validation_functions.py
Labels: feature

#297 Feature/refactor main model
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  tests/cpp_unit_tests/test_main_model_se.cpp
Labels: feature

#303 Feature/fix clang tidy
  tests/cpp_validation_tests/test_validation.cpp
Labels: improvement

#305 feature/remove function pointer code smells
  power_grid_model_c/power_grid_model/include/power_grid_model/component/three_winding_transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_utils.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  tests/c_api_tests/c_api_cpp_handle.hpp
  tests/cpp_unit_tests/test_transformer.cpp
  tests/package_tests/test_c_api_package.cpp
Labels: improvement

#307 Feature/refactor main model io
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/state.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
Labels: improvement

#311 cppcoreguidelines-special-member-functions fix
  .clang-tidy
  power_grid_model_c/power_grid_model/include/power_grid_model/component/appliance.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/base.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/load_gen.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/source.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_all_components.cpp
Labels: feature

#312 Feature/short circuit ybus
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/linear_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/short_circuit_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  tests/cpp_unit_tests/test_math_solver.cpp
  tests/cpp_unit_tests/test_y_bus.cpp
Labels: feature

#313 change to reference values
  .clang-tidy
  tests/cpp_validation_tests/test_validation.cpp
Labels: improvement

#316 Feature/code smells
  .clang-tidy
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/power_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/three_winding_transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/voltage_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/linear_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/math_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/topology.hpp
  tests/benchmark_cpp/benchmark.cpp
  tests/c_api_tests/test_c_api_model.cpp
  tests/cpp_unit_tests/test_fault.cpp
  tests/cpp_unit_tests/test_line.cpp
  tests/cpp_unit_tests/test_link.cpp
  tests/cpp_unit_tests/test_load_gen.cpp
  tests/cpp_unit_tests/test_main_model.cpp
  tests/cpp_unit_tests/test_main_model_static.cpp
  tests/cpp_unit_tests/test_math_solver.cpp
  tests/cpp_unit_tests/test_node.cpp
  tests/cpp_unit_tests/test_power_sensor.cpp
  tests/cpp_unit_tests/test_shunt.cpp
  tests/cpp_unit_tests/test_source.cpp
  tests/cpp_unit_tests/test_sparse_lu_solver.cpp
  tests/cpp_unit_tests/test_sparse_mapping.cpp
  tests/cpp_unit_tests/test_three_phase_tensor.cpp
  tests/cpp_unit_tests/test_three_winding_transformer.cpp
  tests/cpp_unit_tests/test_transformer.cpp
  tests/cpp_unit_tests/test_voltage_sensor.cpp
  tests/cpp_unit_tests/test_y_bus.cpp
  tests/cpp_validation_tests/test_validation.cpp
Labels: improvement

#318 link to boost::headers
  CMakeLists.txt
  power_grid_model_c/power_grid_model/CMakeLists.txt
Labels: improvement

#317 Feature/macro parantheses
  .clang-tidy
  power_grid_model_c/power_grid_model/include/power_grid_model/component/appliance.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/timer.hpp
  tests/cpp_unit_tests/test_math_solver.cpp
  tests/cpp_validation_tests/test_validation.cpp
Labels: improvement

#322 validation on sensors only when state estimation
  src/power_grid_model/validation/validation.py
  tests/unit/validation/test_validation_functions.py
Labels: feature

#309 Feature/short circuit main model
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/appliance.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/base.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch3.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/node.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/power_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/voltage_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/state.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/math_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/short_circuit_solver.hpp
  power_grid_model_c/power_grid_model_c/src/model.cpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_fault.cpp
  tests/cpp_unit_tests/test_main_model.cpp
  tests/cpp_unit_tests/test_main_model_sc.cpp
  tests/cpp_unit_tests/test_main_model_se.cpp
  tests/cpp_unit_tests/test_source.cpp
  tests/cpp_unit_tests/test_three_winding_transformer.cpp
  tests/cpp_unit_tests/test_voltage_sensor.cpp
  tests/cpp_validation_tests/test_validation.cpp
Labels: feature

#326 Fix musl 1.2
  pyproject.toml
Labels: do-not-merge
