Repository PowerGridModel/power-grid-model, pull requests merged in 2023-09, with the labels that each got.

#370 Bugfix/validate infinite sigmas
  src/power_grid_model/core/power_grid_model.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/validation.py
  tests/unit/validation/test_rules.py
  tests/unit/validation/test_validation_functions.py
Labels: bug

#371 allow for infinite voltage measurement sigmas
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  tests/data/state_estimation/high-variance-measurement/input.json
Labels: feature

#367 Feature/pgm serialization python
  .github/conda_pgm_env.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/main.yml
  .github/workflows/sonar.yml
  docs/advanced_documentation/build-guide.md
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/serializer.hpp
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/dataset.h
  pyproject.toml
  setup.py
  src/power_grid_model/_utils.py
  src/power_grid_model/core/buffer_handling.py
  src/power_grid_model/core/data_handling.py
  src/power_grid_model/core/error_handling.py
  src/power_grid_model/core/power_grid_core.py
  src/power_grid_model/core/power_grid_dataset.py
  src/power_grid_model/core/power_grid_meta.py
  src/power_grid_model/core/serialization.py
  src/power_grid_model/errors.py
  src/power_grid_model/utils.py
  src/power_grid_model/validation/errors.py
  src/power_grid_model/validation/validation.py
  tests/c_api_tests/test_serialization.cpp
  tests/unit/test_0Z_model_validation.py
  tests/unit/test_dataset.py
  tests/unit/test_internal_utils.py
  tests/unit/test_power_grid_model.py
  tests/unit/test_serialization.py
  tests/unit/test_utils.py
  tests/unit/utils.py
Labels: feature

#373 Feature/pgm serialization documentation
  docs/advanced_documentation/c-api.md
  docs/api_reference/power-grid-model-c-api-reference.rst
  docs/api_reference/python-api-reference.md
  docs/index.md
  docs/user_manual/serialization.md
  src/power_grid_model/core/serialization.py
  src/power_grid_model/utils.py
  tests/unit/test_serialization.py
  tests/unit/test_utils.py
  tests/unit/utils.py
Labels: documentation

#383 Feature/msgpack from pypi
  pyproject.toml
  setup.py
Labels: dependencies

#386 include nlohmann_json from pypi
  pyproject.toml
  setup.py
Labels: dependencies

#388 Feature/refactor validation tests
  .github/workflows/main.yml
  tests/cpp_validation_tests/test_validation.cpp
Labels: improvement

#393 Move PGM workshop examples
  .readthedocs.yaml
  VERSION
  docs/examples/Make Test Dataset.ipynb
  docs/examples/Make Test Dataset.ipynb.license
  docs/examples/Power Flow Example.ipynb
  docs/examples/Power Flow Example.ipynb.license
  docs/examples/Serialization Example.ipynb
  docs/examples/Serialization Example.ipynb.license
  docs/examples/Short Circuit Example.ipynb
  docs/examples/Short Circuit Example.ipynb.license
  docs/examples/State Estimation Example.ipynb
  docs/examples/State Estimation Example.ipynb.license
  docs/examples/Validation Examples.ipynb
  docs/examples/Validation Examples.ipynb.license
  docs/examples/data/serialized_input.json
  docs/examples/data/serialized_input.json.license
  docs/index.md
Labels: feature
