Repository PowerGridModel/power-grid-model, pull requests merged in 2023-10, with the labels that each got.

#396 fix msgpack serialization to file
  src/power_grid_model/utils.py
Labels: bug

#397 minor improvements to docs + test output
  src/power_grid_model/utils.py
  tests/unit/deprecated/test_end_to_end.py
Labels: documentation, improvement

#402 Replace indptr with sparse and dense grouped index vector
  CMakePresets.json
  README.md
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/common_solver_functions.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_current_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/linear_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/short_circuit_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/sparse_lu_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/topology.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/typing.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_grouped_index_vector.cpp
  tests/cpp_unit_tests/test_math_solver.cpp
  tests/cpp_unit_tests/test_topology.cpp
  tests/cpp_unit_tests/test_typing.cpp
  tests/cpp_unit_tests/test_y_bus.cpp
Labels: improvement

#406 replace sparse with dense representation for components
  .clang-tidy
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/topology.hpp
Labels: improvement

#408 Bugfix/write to file opened in read mode
  src/power_grid_model/utils.py
Labels: bug

#407 Feature/zip sparse grouped idx vector
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/common_solver_functions.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_current_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/linear_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/short_circuit_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/topology.hpp
  tests/cpp_unit_tests/test_grouped_index_vector.cpp
  tests/cpp_unit_tests/test_math_solver.cpp
  tests/cpp_validation_tests/test_validation.cpp
Labels: improvement

#413 rerun the example notebooks
  docs/examples/Validation Examples.ipynb
Labels: documentation

#414 fix sonar code smells
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset_handler.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/line.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/link.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/load_gen.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/node.hpp
Labels: feature

#412 Feature/recombine enumerated zip sequence
  power_grid_model_c/power_grid_model/include/power_grid_model/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/common_solver_functions.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_current_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
Labels: improvement

#418 bump Clang CI on Linux to LLVM-15
  .github/workflows/main.yml
  .github/workflows/sonar.yml
  docs/advanced_documentation/build-guide.md
Labels: bug

#417 fix multiple different code smells
  power_grid_model_c/power_grid_model/include/power_grid_model/component/load_gen.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/block_matrix.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/topology.hpp
Labels: improvement

#416 replace some std::find by std::ranges::find
  docs/advanced_documentation/build-guide.md
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset_handler.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/deserializer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
Labels: improvement
