Repository PowerGridModel/power-grid-model, pull requests merged in 2023-12, with the labels that each got.

#446 extend documentation on dataset validation
  docs/user_manual/calculations.md
  docs/user_manual/data-validator.md
Labels: documentation

#451 Feature/citations readthedocs
  .readthedocs.yaml
  CITATION.cff
  README.md
  docs/index.md
Labels: documentation

#454 Bugfix/fix version
  .github/workflows/main.yml
Labels: bug

#426 update topology to not necessarily go through sparse mapping
  power_grid_model_c/power_grid_model/include/power_grid_model/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/index_mapping.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/sparse_mapping.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/topology.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_index_mapping.cpp
  tests/cpp_unit_tests/test_sparse_mapping.cpp
Labels: feature
