Repository PowerGridModel/power-grid-model, pull requests merged in 2024-07, with the labels that each got.

#671 fix also support empty trafo list in validation
  src/power_grid_model/validation/utils.py
  tests/unit/validation/test_rules.py
Labels: bug

#638 Drop python 3.9
  .github/workflows/check-code-quality.yml
  pyproject.toml
Labels: dependencies

#660 Feature/main model wrapper
  power_grid_model_c/power_grid_model/include/power_grid_model/common/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/component_list.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/base.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_fwd.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_wrapper.hpp
  power_grid_model_c/power_grid_model_c/src/model.cpp
  tests/benchmark_cpp/benchmark.cpp
  tests/benchmark_cpp/fictional_grid_generator.hpp
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_integration_tests/test_main_model_sc.cpp
  tests/cpp_integration_tests/test_main_model_se.cpp
  tests/cpp_integration_tests/test_main_model_static.cpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_component_list.cpp
  tests/cpp_validation_tests/test_validation.cpp
Labels: feature, do-not-merge

#674 [FEATURE] Add simple self_test to Python API
  docs/advanced_documentation/build-guide.md
  docs/quickstart.md
  src/power_grid_model/utils.py
  tests/unit/test_utils.py
Labels: improvement

#675 Feature/test row based dataset
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  src/power_grid_model/data_types.py
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_container.cpp
  tests/cpp_unit_tests/test_dataset.cpp
Labels: improvement
