Repository PowerGridModel/power-grid-model, pull requests merged in 2024-11, with the labels that each got.

#818 Feature/resolve comments optional ids
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  tests/native_api_tests/test_api_model.cpp
Labels: improvement

#771 Feature / columnar data optional id field support in update data
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/three_phase_tensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch3.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/load_gen.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/power_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/shunt.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/source.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/three_winding_transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_tap_regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/voltage_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/state_queries.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  src/power_grid_model/_utils.py
  src/power_grid_model/validation/errors.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/utils.py
  src/power_grid_model/validation/validation.py
  tests/cpp_integration_tests/CMakeLists.txt
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_integration_tests/test_main_model_static.cpp
  tests/cpp_unit_tests/test_container.cpp
  tests/native_api_tests/test_api_model.cpp
  tests/unit/test_power_grid_model.py
  tests/unit/validation/test_batch_validation.py
  tests/unit/validation/test_utils.py
  tests/unit/validation/test_validation_functions.py
Labels: feature

#819 Feature/support for optional IDs per component type
  .pre-commit-config.yaml
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  tests/native_api_tests/test_api_model.cpp
  tests/unit/test_optional_ids.py
  tests/unit/test_power_grid_model.py
Labels: feature

#814 Feature/Update documentation for optional update IDs
  docs/examples/Asymmetric Calculation Example.ipynb
  docs/examples/Make Test Dataset.ipynb
  docs/examples/Power Flow Example.ipynb
  docs/examples/Serialization Example.ipynb
  docs/examples/Short Circuit Example.ipynb
  docs/examples/State Estimation Example.ipynb
  docs/examples/Transformer Examples.ipynb
  docs/examples/Validation Examples.ipynb
  docs/user_manual/components.md
Labels: documentation

#811 Throw error on wrong dtype
  src/power_grid_model/core/buffer_handling.py
  tests/unit/test_data_handling.py
  tests/unit/test_dataset.py
Labels: feature

#787 Feature/private core module
  code_generation/templates/src/power_grid_model/_core/dataset_class_maps.py.jinja
  docs/examples/Power Flow Example.ipynb
  docs/examples/Validation Examples.ipynb
  setup.py
  src/power_grid_model/__init__.py
  src/power_grid_model/_core/__init__.py
  src/power_grid_model/_core/buffer_handling.py
  src/power_grid_model/_core/data_handling.py
  src/power_grid_model/_core/dataset_definitions.py
  src/power_grid_model/_core/error_handling.py
  src/power_grid_model/_core/index_integer.py
  src/power_grid_model/_core/options.py
  src/power_grid_model/_core/power_grid_core.py
  src/power_grid_model/_core/power_grid_dataset.py
  src/power_grid_model/_core/power_grid_meta.py
  src/power_grid_model/_core/power_grid_model.py
  src/power_grid_model/_core/serialization.py
  src/power_grid_model/_utils.py
  src/power_grid_model/data_types.py
  src/power_grid_model/typing.py
  src/power_grid_model/utils.py
  src/power_grid_model/validation/utils.py
  tests/unit/deprecated/test_end_to_end.py
  tests/unit/test_buffer_handling.py
  tests/unit/test_data_handling.py
  tests/unit/test_dataset.py
  tests/unit/test_error_handling.py
  tests/unit/test_internal_utils.py
  tests/unit/test_utils.py
  tests/unit/utils.py
  tests/unit/validation/test_validation_functions.py
Labels: improvement, do-not-merge

#822 make validation core functions private
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/utils.py
  src/power_grid_model/validation/validation.py
  tests/unit/validation/test_input_validation.py
  tests/unit/validation/test_utils.py
  tests/unit/validation/test_validation_functions.py
Labels: improvement

#825 Fix/Nightly build
  tests/cpp_integration_tests/test_main_model.cpp
Labels: improvement

#823 Release/v1.10.x
  .github/workflows/sonar.yml
  VERSION
  code_generation/templates/src/power_grid_model/_core/dataset_class_maps.py.jinja
  docs/examples/Power Flow Example.ipynb
  docs/examples/Validation Examples.ipynb
  setup.py
  src/power_grid_model/__init__.py
  src/power_grid_model/_core/__init__.py
  src/power_grid_model/_core/buffer_handling.py
  src/power_grid_model/_core/data_handling.py
  src/power_grid_model/_core/dataset_definitions.py
  src/power_grid_model/_core/error_handling.py
  src/power_grid_model/_core/index_integer.py
  src/power_grid_model/_core/options.py
  src/power_grid_model/_core/power_grid_core.py
  src/power_grid_model/_core/power_grid_dataset.py
  src/power_grid_model/_core/power_grid_meta.py
  src/power_grid_model/_core/power_grid_model.py
  src/power_grid_model/_core/serialization.py
  src/power_grid_model/_utils.py
  src/power_grid_model/data_types.py
  src/power_grid_model/typing.py
  src/power_grid_model/utils.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/utils.py
  src/power_grid_model/validation/validation.py
  tests/unit/deprecated/test_end_to_end.py
  tests/unit/test_buffer_handling.py
  tests/unit/test_data_handling.py
  tests/unit/test_dataset.py
  tests/unit/test_error_handling.py
  tests/unit/test_internal_utils.py
  tests/unit/test_utils.py
  tests/unit/utils.py
  tests/unit/validation/test_input_validation.py
  tests/unit/validation/test_utils.py
  tests/unit/validation/test_validation_functions.py
Labels: feature

#824 Feature / use span instead of reference wrapper for cache sequence
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
Labels: improvement

#698 Feature / Updated transformer weight before transformer ranking
  docs/user_manual/calculations.md
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature, improvement

#831 Feature/Use None instead of Optional
  code_generation/meta_data.py
  src/power_grid_model/_core/error_handling.py
  src/power_grid_model/_core/power_grid_core.py
  src/power_grid_model/_core/power_grid_dataset.py
  src/power_grid_model/_core/power_grid_model.py
  src/power_grid_model/_utils.py
  src/power_grid_model/utils.py
  src/power_grid_model/validation/assertions.py
  src/power_grid_model/validation/errors.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/utils.py
  src/power_grid_model/validation/validation.py
  tests/unit/test_serialization.py
  tests/unit/utils.py
Labels: improvement

#832 Feature / Step-up transformer tap changer support updated ranking
  power_grid_model_c/power_grid_model/include/power_grid_model/common/enum.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  src/power_grid_model/_core/error_handling.py
  src/power_grid_model/errors.py
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-any/input.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-any/sym_output_batch.json
  tests/unit/test_error_handling.py
  tests/unit/utils.py
Labels: feature

#844 Resolve deprecated sonar cloud usage
  .github/workflows/sonar.yml
Labels: improvement

#845 Adding message to `NotObservableError` when no voltage sensor present
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/observability.hpp
Labels: feature

#841 Keep only important integration tests: step 2
  docs/user_manual/components.md
  tests/cpp_integration_tests/CMakeLists.txt
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_integration_tests/test_main_model_sc.cpp
  tests/data/power_flow/dummy-test-batch-incomplete-input/asym_output_batch.json
  tests/data/power_flow/dummy-test-batch-incomplete-input/asym_output_batch.json.license
  tests/data/power_flow/dummy-test-batch-incomplete-input/input.json
  tests/data/short_circuit/branch_source_single_phase_to_ground_c_maximum/input.json
  tests/data/short_circuit/branch_source_single_phase_to_ground_c_maximum/input.json.license
  tests/data/short_circuit/branch_source_single_phase_to_ground_c_maximum/params.json
  tests/data/short_circuit/branch_source_single_phase_to_ground_c_maximum/params.json.license
  tests/data/short_circuit/branch_source_single_phase_to_ground_c_maximum/sc_output.json
  tests/data/short_circuit/branch_source_single_phase_to_ground_c_maximum/sc_output.json.license
  tests/data/short_circuit/branch_source_single_phase_to_ground_c_maximum/sc_output_batch.json
  tests/data/short_circuit/branch_source_single_phase_to_ground_c_maximum/sc_output_batch.json.license
  tests/data/short_circuit/branch_source_single_phase_to_ground_c_maximum/update_batch.json
  tests/data/short_circuit/branch_source_single_phase_to_ground_c_maximum/update_batch.json.license
  tests/data/short_circuit/single_node_source_three_phase_c_maximum/input.json
  tests/data/short_circuit/single_node_source_three_phase_c_maximum/input.json.license
  tests/data/short_circuit/single_node_source_three_phase_c_maximum/params.json
  tests/data/short_circuit/single_node_source_three_phase_c_maximum/params.json.license
  tests/data/short_circuit/single_node_source_three_phase_c_maximum/sc_output.json
  tests/data/short_circuit/single_node_source_three_phase_c_maximum/sc_output.json.license
  tests/data/short_circuit/single_node_source_three_phase_c_minimum/input.json
  tests/data/short_circuit/single_node_source_three_phase_c_minimum/input.json.license
  tests/data/short_circuit/single_node_source_three_phase_c_minimum/params.json
  tests/data/short_circuit/single_node_source_three_phase_c_minimum/params.json.license
  tests/data/short_circuit/single_node_source_three_phase_c_minimum/sc_output.json
  tests/data/short_circuit/single_node_source_three_phase_c_minimum/sc_output.json.license
  tests/native_api_tests/test_api_model.cpp
Labels: improvement

#846 Feature/only important integration tests 3
  tests/cpp_integration_tests/CMakeLists.txt
  tests/cpp_integration_tests/test_main_model_se.cpp
  tests/data/state_estimation/line-power-sensor/input.json
  tests/data/state_estimation/line-power-sensor/input.json.license
  tests/data/state_estimation/line-power-sensor/params.json
  tests/data/state_estimation/line-power-sensor/params.json.license
  tests/data/state_estimation/line-power-sensor/sym_output.json
  tests/data/state_estimation/line-power-sensor/sym_output.json.license
  tests/data/state_estimation/node-injection-with-injection-sensor-sym-sensors/asym_output.json
  tests/data/state_estimation/node-injection-with-injection-sensor-sym-sensors/asym_output.json.license
  tests/data/state_estimation/node-injection-with-injection-sensor-sym-sensors/input.json
  tests/data/state_estimation/node-injection-with-injection-sensor-sym-sensors/input.json.license
  tests/data/state_estimation/node-injection-with-injection-sensor-sym-sensors/params.json
  tests/data/state_estimation/node-injection-with-injection-sensor-sym-sensors/params.json.license
  tests/data/state_estimation/node-injection-with-injection-sensor-sym-sensors/sym_output.json
  tests/data/state_estimation/node-injection-with-injection-sensor-sym-sensors/sym_output.json.license
  tests/data/state_estimation/node-injection-wo-injection-sensor-sym-sensors/asym_output.json
  tests/data/state_estimation/node-injection-wo-injection-sensor-sym-sensors/asym_output.json.license
  tests/data/state_estimation/node-injection-wo-injection-sensor-sym-sensors/input.json
  tests/data/state_estimation/node-injection-wo-injection-sensor-sym-sensors/input.json.license
  tests/data/state_estimation/node-injection-wo-injection-sensor-sym-sensors/params.json
  tests/data/state_estimation/node-injection-wo-injection-sensor-sym-sensors/params.json.license
  tests/data/state_estimation/node-injection-wo-injection-sensor-sym-sensors/sym_output.json
  tests/data/state_estimation/node-injection-wo-injection-sensor-sym-sensors/sym_output.json.license
  tests/data/state_estimation/single-node-source-asym-voltage-sensor-no-angle/asym_output.json
  tests/data/state_estimation/single-node-source-asym-voltage-sensor-no-angle/asym_output.json.license
  tests/data/state_estimation/single-node-source-asym-voltage-sensor-no-angle/input.json
  tests/data/state_estimation/single-node-source-asym-voltage-sensor-no-angle/input.json.license
  tests/data/state_estimation/single-node-source-asym-voltage-sensor-no-angle/params.json
  tests/data/state_estimation/single-node-source-asym-voltage-sensor-no-angle/params.json.license
  tests/data/state_estimation/single-node-source-asym-voltage-sensor-no-angle/sym_output.json
  tests/data/state_estimation/single-node-source-asym-voltage-sensor-no-angle/sym_output.json.license
  tests/data/state_estimation/single-node-source-asym-voltage-sensor/asym_output.json
  tests/data/state_estimation/single-node-source-asym-voltage-sensor/asym_output.json.license
  tests/data/state_estimation/single-node-source-asym-voltage-sensor/input.json
  tests/data/state_estimation/single-node-source-asym-voltage-sensor/input.json.license
  tests/data/state_estimation/single-node-source-asym-voltage-sensor/params.json
  tests/data/state_estimation/single-node-source-asym-voltage-sensor/params.json.license
  tests/data/state_estimation/single-node-source-asym-voltage-sensor/sym_output.json
  tests/data/state_estimation/single-node-source-asym-voltage-sensor/sym_output.json.license
  tests/data/state_estimation/single-node-source-sym-voltage-sensor-no-angle/asym_output.json
  tests/data/state_estimation/single-node-source-sym-voltage-sensor-no-angle/asym_output.json.license
  tests/data/state_estimation/single-node-source-sym-voltage-sensor-no-angle/input.json
  tests/data/state_estimation/single-node-source-sym-voltage-sensor-no-angle/input.json.license
  tests/data/state_estimation/single-node-source-sym-voltage-sensor-no-angle/params.json
  tests/data/state_estimation/single-node-source-sym-voltage-sensor-no-angle/params.json.license
  tests/data/state_estimation/single-node-source-sym-voltage-sensor-no-angle/sym_output.json
  tests/data/state_estimation/single-node-source-sym-voltage-sensor-no-angle/sym_output.json.license
  tests/data/state_estimation/single-node-source-sym-voltage-sensor/asym_output.json
  tests/data/state_estimation/single-node-source-sym-voltage-sensor/asym_output.json.license
  tests/data/state_estimation/single-node-source-sym-voltage-sensor/input.json
  tests/data/state_estimation/single-node-source-sym-voltage-sensor/input.json.license
  tests/data/state_estimation/single-node-source-sym-voltage-sensor/params.json
  tests/data/state_estimation/single-node-source-sym-voltage-sensor/params.json.license
  tests/data/state_estimation/single-node-source-sym-voltage-sensor/sym_output.json
  tests/data/state_estimation/single-node-source-sym-voltage-sensor/sym_output.json.license
  tests/native_api_tests/CMakeLists.txt
  tests/native_api_tests/test_api_model.cpp
  tests/native_api_tests/test_api_model_update.cpp
Labels: improvement
