Repository PowerGridModel/power-grid-model, pull requests merged in 2024-04, with the labels that each got.

#561 revert 531
  .github/workflows/main.yml
Labels: bug

#558 Feature/transformer ranking step 4
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_transformer_tap_regulator.cpp
Labels: feature

#565 refactor main core + initial setup for tap regulator input/output
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/serializer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch3.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/three_winding_transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_tap_regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/topology.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  src/power_grid_model/core/error_handling.py
  src/power_grid_model/errors.py
  tests/cpp_integration_tests/test_main_model_se.cpp
  tests/cpp_unit_tests/test_line.cpp
  tests/cpp_unit_tests/test_link.cpp
  tests/cpp_unit_tests/test_transformer_tap_regulator.cpp
  tests/unit/test_error_handling.py
  tests/unit/utils.py
Labels: improvement

#567 Unit tests for transformer ranking
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#569 Feature/transformer ranking test 1
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#570 Added size checks before retrieve_info; updated the test
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#572 [Feature] common state queries + transformer concept
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch3.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/three_winding_transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_utils.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/state_queries.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/topology.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
Labels: improvement

#573 Transformer edge fix
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#575 run citations workflow when current workflow changes
  .github/workflows/citations.yml
Labels: documentation

#562 Transformer ranking part 1
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  src/power_grid_model/core/error_handling.py
  src/power_grid_model/errors.py
  tests/cpp_unit_tests/test_optimizer.cpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/unit/test_error_handling.py
  tests/unit/utils.py
Labels: feature

#577 [FEATURE] add support for same-ranked transformers
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: bug

#578 Feature/container + main core improvements
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/enum.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/base.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/component.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_utils.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/math_state.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  tests/cpp_unit_tests/test_all_components.cpp
  tests/cpp_unit_tests/test_container.cpp
  tests/cpp_unit_tests/test_grouped_index_vector.cpp
Labels: improvement

#557 Tap position optimizer outer loop
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_tap_regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/state_queries.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/base_optimizer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/optimizer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_optimizer.cpp
  tests/cpp_unit_tests/test_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#581 fix missed checkin
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
Labels: feature
