Repository PowerGridModel/power-grid-model, pull requests merged in 2024-08, with the labels that each got.

#681 Feature/calculation type in options
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/meta_data.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/enum.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_fwd.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model_c/src/model.cpp
  tests/benchmark_cpp/benchmark.cpp
  tests/benchmark_cpp/fictional_grid_generator.hpp
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_integration_tests/test_main_model_sc.cpp
  tests/cpp_integration_tests/test_main_model_se.cpp
  tests/cpp_integration_tests/test_main_model_static.cpp
  tests/cpp_validation_tests/test_validation.cpp
Labels: improvement

#668 Feature / Binary search in Automatic Tap Changer
  docs/examples/Transformer Examples.ipynb
  docs/user_manual/calculations.md
  power_grid_model_c/power_grid_model/include/power_grid_model/common/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/enum.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_fwd.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/optimizer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/basics.h
  power_grid_model_c/power_grid_model_c/src/model.cpp
  src/power_grid_model/core/error_handling.py
  src/power_grid_model/enum.py
  src/power_grid_model/errors.py
  tests/c_api_tests/test_c_api_model.cpp
  tests/cpp_unit_tests/test_optimizer.cpp
  tests/cpp_unit_tests/test_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/cpp_validation_tests/test_validation.cpp
  tests/unit/test_0Z_model_validation.py
  tests/unit/test_error_handling.py
Labels: feature

#678 Feature/columnar dataset
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  tests/cpp_unit_tests/test_dataset.cpp
Labels: feature

#684 remove erroneously added unused and test logic after #668
  src/power_grid_model/errors.py
  tests/cpp_validation_tests/test_validation.cpp
  tests/unit/test_0Z_model_validation.py
  tests/unit/test_error_handling.py
Labels: bug

#682 Feature/calculation type options in tests
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  tests/benchmark_cpp/benchmark.cpp
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_integration_tests/test_main_model_sc.cpp
  tests/cpp_integration_tests/test_main_model_se.cpp
  tests/cpp_validation_tests/test_validation.cpp
Labels: improvement

#690 Bugfix/dont crash on invalid homogeneous batch dataset
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  tests/data/power_flow/non-existent-id-update-batch/input.json
  tests/data/power_flow/non-existent-id-update-batch/input.json.license
  tests/data/power_flow/non-existent-id-update-batch/params.json
  tests/data/power_flow/non-existent-id-update-batch/params.json.license
  tests/data/power_flow/non-existent-id-update-batch/sym_output_batch.json
  tests/data/power_flow/non-existent-id-update-batch/sym_output_batch.json.license
  tests/data/power_flow/non-existent-id-update-batch/update_batch.json
  tests/data/power_flow/non-existent-id-update-batch/update_batch.json.license
Labels: bug

#689 Path changes to cmake files
  cmake/export_power_grid_model.cmake
  cmake/pgm_version.cmake
  tests/cpp_validation_tests/CMakeLists.txt
Labels: improvement

#697 Feature/enable mypy for users
  pyproject.toml
  src/power_grid_model/py.typed
Labels: feature

#663 add columnar data to data types (but don't use yet)
  src/power_grid_model/_utils.py
  src/power_grid_model/core/buffer_handling.py
  src/power_grid_model/core/data_handling.py
  src/power_grid_model/core/power_grid_dataset.py
  src/power_grid_model/core/power_grid_model.py
  src/power_grid_model/core/serialization.py
  src/power_grid_model/data_types.py
  src/power_grid_model/utils.py
  src/power_grid_model/validation/utils.py
  tests/unit/test_serialization.py
  tests/unit/validation/test_utils.py
Labels: feature

#701 license for py.typed
  src/power_grid_model/py.typed
Labels: bug

#703 BugFix / Handle access violation to unconnected-regulated transformers
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-any/input.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-any/sym_output_batch.json
Labels: bug
