Repository PowerGridModel/power-grid-model, pull requests merged in 2024-12, with the labels that each got.

#843 Optional ID refactor: part 3
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/core_utils.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
Labels: improvement

#850 fix nightly build clang-tidy
  tests/cpp_unit_tests/test_math_solver_pf.hpp
  tests/cpp_unit_tests/test_math_solver_se.hpp
Labels: bug

#848 Keep only important integration tests: step 5
  build.sh
  docs/advanced_documentation/build-guide.md
  docs/advanced_documentation/c-api.md
  power_grid_model_c/power_grid_model/include/power_grid_model/common/enum.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/basics.h
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/options.h
  power_grid_model_c/power_grid_model_c/src/model.cpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/dataset.hpp
  sonar-project.properties
  tests/CMakeLists.txt
  tests/cpp_integration_tests/CMakeLists.txt
  tests/cpp_integration_tests/test_entry_point.cpp
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_unit_tests/test_math_solver_pf.hpp
  tests/cpp_unit_tests/test_math_solver_pf_newton_raphson.cpp
  tests/cpp_validation_tests/test_validation.cpp
  tests/native_api_tests/test_api_model.cpp
  tests/native_api_tests/test_api_model_update.cpp
  tests/native_api_tests/test_api_serialization.cpp
Labels: improvement

#849 MessagePack deserialization: improve error messages
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/deserializer.hpp
Labels: improvement

#851 resolve sonar cloud issues
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/dataset.hpp
  tests/cpp_validation_tests/test_validation.cpp
  tests/native_api_tests/test_api_model.cpp
  tests/native_api_tests/test_api_model_update.cpp
Labels: improvement

#852 Sparse matrix error: repro case for not using numerical pivoting
  tests/data/state_estimation/leaf-without-power-sensor/input.json
  tests/data/state_estimation/leaf-without-power-sensor/input.json.license
  tests/data/state_estimation/leaf-without-power-sensor/params.json
  tests/data/state_estimation/leaf-without-power-sensor/params.json.license
  tests/data/state_estimation/leaf-without-power-sensor/sym_output.json
  tests/data/state_estimation/leaf-without-power-sensor/sym_output.json.license
  tests/data/state_estimation/middle-without-power-sensor/input.json
  tests/data/state_estimation/middle-without-power-sensor/input.json.license
  tests/data/state_estimation/middle-without-power-sensor/params.json
  tests/data/state_estimation/middle-without-power-sensor/params.json.license
  tests/data/state_estimation/middle-without-power-sensor/sym_output.json
  tests/data/state_estimation/middle-without-power-sensor/sym_output.json.license
  tests/unit/utils.py
Labels: bug

#854 Sparse matrix error: more complete repro case
  tests/data/state_estimation/middle-without-power-sensor/input.json
  tests/unit/validation/test_input_validation.py
Labels: bug

#856 get libboost-headers from pypi
  pyproject.toml
  setup.py
Labels: dependencies, improvement

#855 Feature/deserialized api tests
  .pre-commit-config.yaml
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/dataset.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/handle.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/serialization.hpp
  tests/cpp_unit_tests/test_math_solver_common.hpp
  tests/cpp_unit_tests/test_math_solver_pf.hpp
  tests/cpp_unit_tests/test_math_solver_se.hpp
  tests/cpp_unit_tests/test_optimizer.hpp
  tests/cpp_validation_tests/test_validation.cpp
  tests/native_api_tests/load_dataset.hpp
  tests/native_api_tests/test_api_model.cpp
  tests/native_api_tests/test_api_model_update.cpp
Labels: improvement

#859 also add launch configuration for windows
  .vscode/launch.json
Labels: improvement
