Repository PowerGridModel/power-grid-model, pull requests merged in 2024-09, with the labels that each got.

#709 Update quickstart.md
  docs/quickstart.md
Labels: documentation

#708 Feature/columnar data serialization
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/meta_data.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/deserializer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/serializer.hpp
  tests/cpp_unit_tests/test_dataset.cpp
  tests/cpp_unit_tests/test_deserializer.cpp
  tests/cpp_unit_tests/test_serializer.cpp
Labels: feature

#712 Feature / Add columnar data support in main model
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/iterator_like_concepts.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_unit_tests/test_dataset.cpp
Labels: feature

#719 Feature / Rename API tests
  sonar-project.properties
  tests/CMakeLists.txt
  tests/native_api_tests/CMakeLists.txt
  tests/native_api_tests/test_api_meta_data.cpp
  tests/native_api_tests/test_api_model.cpp
  tests/native_api_tests/test_api_serialization.cpp
  tests/native_api_tests/test_entry_point.cpp
Labels: improvement

#711 Feature / Columnar data C API
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/sparse_ordering.hpp
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/dataset.h
  power_grid_model_c/power_grid_model_c/src/dataset.cpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/buffer.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/dataset.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/handle.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/meta_data.hpp
  tests/cpp_unit_tests/test_dataset.cpp
  tests/cpp_unit_tests/test_deserializer.cpp
  tests/cpp_unit_tests/test_observability.cpp
  tests/cpp_unit_tests/test_transformer_tap_regulator.cpp
  tests/native_api_tests/test_api_model.cpp
  tests/native_api_tests/test_api_serialization.cpp
Labels: feature

#745 Update README.md
  README.md
Labels: documentation

#750 add check code quality + citations to nightly
  .github/workflows/check-code-quality.yml
  .github/workflows/citations.yml
  .github/workflows/nightly.yml
  .github/workflows/reuse-compliance.yml
Labels: improvement

#746 Feature / Add enum options to deserialize relevant attributes
  src/power_grid_model/__init__.py
  src/power_grid_model/_utils.py
  src/power_grid_model/core/serialization.py
  src/power_grid_model/typing.py
  tests/unit/test_internal_utils.py
  tests/unit/test_serialization.py
  tests/unit/validation/test_batch_validation.py
  tests/unit/validation/test_input_validation.py
Labels: feature
