Repository PowerGridModel/power-grid-model, pull requests merged in 2024-02, with the labels that each got.

#485 bump cibuildwheel to `v2.16.5
  .github/workflows/main.yml
Labels: bug

#482 Add notebook example of asymmetric calculations.
  docs/examples/Asymmetric Calculation Example.ipynb
  docs/examples/Asymmetric Calculation Example.ipynb.license
  docs/index.md
Labels: documentation

#488 NRSE documentation
  docs/user_manual/calculations.md
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/basics.h
Labels: documentation

#494 Feature/test unbalanced power measurement
  tests/data/state_estimation/unbalanced-power-measurements-iterative-linear/input.json
  tests/data/state_estimation/unbalanced-power-measurements-iterative-linear/input.json.license
  tests/data/state_estimation/unbalanced-power-measurements-iterative-linear/params.json
  tests/data/state_estimation/unbalanced-power-measurements-iterative-linear/params.json.license
  tests/data/state_estimation/unbalanced-power-measurements-iterative-linear/sym_output_batch.json
  tests/data/state_estimation/unbalanced-power-measurements-iterative-linear/sym_output_batch.json.license
  tests/data/state_estimation/unbalanced-power-measurements-iterative-linear/update_batch.json
  tests/data/state_estimation/unbalanced-power-measurements-iterative-linear/update_batch.json.license
  tests/data/state_estimation/unbalanced-power-measurements-newton-raphson/input.json
  tests/data/state_estimation/unbalanced-power-measurements-newton-raphson/input.json.license
  tests/data/state_estimation/unbalanced-power-measurements-newton-raphson/params.json
  tests/data/state_estimation/unbalanced-power-measurements-newton-raphson/params.json.license
  tests/data/state_estimation/unbalanced-power-measurements-newton-raphson/sym_output_batch.json
  tests/data/state_estimation/unbalanced-power-measurements-newton-raphson/sym_output_batch.json.license
  tests/data/state_estimation/unbalanced-power-measurements-newton-raphson/update_batch.json
  tests/data/state_estimation/unbalanced-power-measurements-newton-raphson/update_batch.json.license
Labels: feature

#495 Finalize NRSE
  power_grid_model_c/power_grid_model/include/power_grid_model/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/block_matrix.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_se_solver.hpp
  tests/cpp_unit_tests/test_grouped_index_vector.cpp
  tests/data/state_estimation/distribution-case/input.json
  tests/data/state_estimation/distribution-case/params.json
  tests/data/state_estimation/distribution-case/sym_output_batch.json
  tests/data/state_estimation/distribution-case/update_batch.json
  tests/data/state_estimation/sensor-update-il/input.json
  tests/data/state_estimation/sensor-update-il/input.json.license
  tests/data/state_estimation/sensor-update-il/params.json
  tests/data/state_estimation/sensor-update-il/params.json.license
  tests/data/state_estimation/sensor-update-il/sym_output_batch.json
  tests/data/state_estimation/sensor-update-il/sym_output_batch.json.license
  tests/data/state_estimation/sensor-update-il/update_batch.json
  tests/data/state_estimation/sensor-update-il/update_batch.json.license
  tests/data/state_estimation/sensor-update-nr/input.json
  tests/data/state_estimation/sensor-update-nr/input.json.license
  tests/data/state_estimation/sensor-update-nr/params.json
  tests/data/state_estimation/sensor-update-nr/params.json.license
  tests/data/state_estimation/sensor-update-nr/sym_output_batch.json
  tests/data/state_estimation/sensor-update-nr/sym_output_batch.json.license
  tests/data/state_estimation/sensor-update-nr/update_batch.json
  tests/data/state_estimation/sensor-update-nr/update_batch.json.license
  tests/data/state_estimation/sensor-update/input.json
  tests/data/state_estimation/sensor-update/params.json
  tests/data/state_estimation/sensor-update/sym_output_batch.json
  tests/data/state_estimation/sensor-update/update_batch.json
  tests/data/state_estimation/single-line-load-il/input.json
  tests/data/state_estimation/single-line-load-il/input.json.license
  tests/data/state_estimation/single-line-load-il/params.json
  tests/data/state_estimation/single-line-load-il/params.json.license
  tests/data/state_estimation/single-line-load-il/sym_output.json
  tests/data/state_estimation/single-line-load-il/sym_output.json.license
  tests/data/state_estimation/single-line-load/params.json
  tests/unit/test_0Z_model_validation.py
  tests/unit/utils.py
Labels: bug

#499 Release v1.7.0: Newton-Raphson State Estimation
  VERSION
  docs/user_manual/calculations.md
  power_grid_model_c/power_grid_model_c/src/model.cpp
  tests/data/state_estimation/1os2msr-no-angle/params.json
  tests/data/state_estimation/1os2msr/params.json
  tests/data/state_estimation/distribution-case/params.json
  tests/data/state_estimation/dummy-test-sym/params.json
  tests/data/state_estimation/high-variance-measurement/params.json
  tests/data/state_estimation/node-injection-sensor-and-zero-injection/params.json
  tests/data/state_estimation/residual-test/params.json
  tests/data/state_estimation/sensor-update-nr/params.json
  tests/data/state_estimation/three_winding_transformer/params.json
  tests/data/state_estimation/transmission-case/params.json
  tests/data/state_estimation/unbalanced-power-measurements-newton-raphson/params.json
Labels: feature
