Repository PowerGridModel/power-grid-model, pull requests merged in 2024-03, with the labels that each got.

#503 Feature/Updated validation to allow for missing sigma
  docs/user_manual/components.md
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/validation.py
  tests/unit/validation/test_validation_functions.py
Labels: feature

#522 Fix MacOS CI setup phase
  .github/workflows/main.yml
Labels: bug

#532 add merge queue stuff for CI
  .github/workflows/check-code-quality.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/main.yml
  .github/workflows/reuse-compliance.yml
  .github/workflows/sonar.yml
Labels: feature

#504 Sorting optimization
  power_grid_model_c/power_grid_model/include/power_grid_model/index_mapping.hpp
  tests/cpp_unit_tests/test_index_mapping.cpp
Labels: improvement

#536 add DCO for merge groups
  .github/workflows/dco-merge-group.yml
  .github/workflows/main.yml
Labels: improvement

#539 Fix/General re-touching of the documentation
  docs/examples/Asymmetric Calculation Example.ipynb
  docs/examples/Power Flow Example.ipynb
  docs/examples/Transformer Examples.ipynb
  docs/index.md
  docs/quickstart.md
  docs/user_manual/calculations.md
  docs/user_manual/components.md
  docs/user_manual/data-model.md
  docs/user_manual/dataset-terminology.md
  docs/user_manual/model-validation.md
Labels: documentation

#544 separate test executable for quickly compilable unit tests and long
  build.sh
  docs/advanced_documentation/build-guide.md
  docs/contribution/folder-structure.md
  sonar-project.properties
  tests/CMakeLists.txt
  tests/cpp_integration_tests/CMakeLists.txt
  tests/cpp_integration_tests/test_entry_point.cpp
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_integration_tests/test_main_model_sc.cpp
  tests/cpp_integration_tests/test_main_model_se.cpp
  tests/cpp_integration_tests/test_main_model_static.cpp
  tests/cpp_integration_tests/test_math_solver.cpp
  tests/cpp_unit_tests/CMakeLists.txt
Labels: improvement

#550 Preparing steps 2-3 so that step 1 can start
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
Labels: feature

#545 Feature/Transformer ranking - Step 2-3
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
Labels: feature

#555 add test test case for state estimation bug #554
  tests/data/state_estimation/sensor-update-initially-empty/input.json
  tests/data/state_estimation/sensor-update-initially-empty/input.json.license
  tests/data/state_estimation/sensor-update-initially-empty/params.json
  tests/data/state_estimation/sensor-update-initially-empty/params.json.license
  tests/data/state_estimation/sensor-update-initially-empty/sym_output_batch.json
  tests/data/state_estimation/sensor-update-initially-empty/sym_output_batch.json.license
  tests/data/state_estimation/sensor-update-initially-empty/update_batch.json
  tests/data/state_estimation/sensor-update-initially-empty/update_batch.json.license
Labels: improvement

#552 documentation for error types
  docs/api_reference/python-api-reference.md
  docs/examples/Validation Examples.ipynb
Labels: documentation

#553 also run macos arm64 in merge group
  .github/workflows/main.yml
Labels: improvement
