Repository PowerGridModel/power-grid-model, pull requests merged in 2024-06, with the labels that each got.

#615 [Feature] add automatic tap adjustment to the transformer notebook
  docs/examples/Power Flow Example.ipynb
  docs/examples/Transformer Examples.ipynb
  src/power_grid_model/__init__.py
Labels: documentation

#618 [Feature] make tap regulator input attributes always required
  docs/user_manual/components.md
Labels: documentation

#617 Feature / State restoration after exception in optimizer
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: bug

#620 [FEATURE] basic validation checks for tap regulator
  src/power_grid_model/validation/errors.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/validation.py
  tests/unit/validation/test_input_validation.py
  tests/unit/validation/test_rules.py
Labels: feature

#632 Revert "temporarily add DCO check"
  .github/workflows/dco-check.yml
  .github/workflows/main.yml
Labels: dependencies

#635 [Fix] handle nullptr on serialization error
  src/power_grid_model/core/power_grid_core.py
  tests/c_api_tests/test_serialization.cpp
Labels: bug

#634 Feature/validation check control side tap
  src/power_grid_model/validation/errors.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/utils.py
  src/power_grid_model/validation/validation.py
  tests/unit/validation/test_errors.py
  tests/unit/validation/test_input_validation.py
  tests/unit/validation/test_validation_functions.py
Labels: feature

#637 [Release] v1.8.0
  VERSION
  docs/examples/Transformer Examples.ipynb
  docs/user_manual/calculations.md
  power_grid_model_c/power_grid_model_c/src/model.cpp
  src/power_grid_model/core/power_grid_model.py
  tests/c_api_tests/test_c_api_model.cpp
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-minimal-max/params.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-minimal-min/params.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-any/params.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-line-drop-any/params.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-line-drop-max/params.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-line-drop-min/params.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-max/params.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-min/params.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-tight-bands/params.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-max-voltage-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-min-voltage-tap/params.json
  tests/unit/test_error_handling.py
Labels: feature

#440 Feature/minimum degree topology
  power_grid_model_c/power_grid_model/include/power_grid_model/sparse_ordering.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/topology.hpp
  tests/benchmark_cpp/fictional_grid_generator.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_sparse_ordering.cpp
  tests/cpp_unit_tests/test_topology.cpp
  tests/cpp_validation_tests/test_validation.cpp
Labels: improvement

#649 Feature/improve and test floating points in exception message
  docs/examples/Power Flow Example.ipynb
  docs/examples/Serialization Example.ipynb
  docs/examples/State Estimation Example.ipynb
  docs/examples/Validation Examples.ipynb
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_exceptions.cpp
  tests/unit/test_error_handling.py
  tests/unit/test_power_grid_model.py
Labels: bug

#650 Update test_serialization.cpp
  tests/c_api_tests/test_serialization.cpp
Labels: improvement

#652 Feature / Revisit transformer ranking and fix multi-source issue
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: bug, feature
