Repository PowerGridModel/power-grid-model, pull requests merged in 2024-05, with the labels that each got.

#583 Renaming `MathOutput` to `SolverOutput`
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/appliance.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch3.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/load_gen.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/shunt.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/source.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/common_solver_functions.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_current_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/linear_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/math_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/measured_values.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/short_circuit_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/base_optimizer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_integration_tests/test_main_model_sc.cpp
  tests/cpp_integration_tests/test_main_model_se.cpp
  tests/cpp_integration_tests/test_math_solver.cpp
  tests/cpp_unit_tests/test_line.cpp
  tests/cpp_unit_tests/test_load_gen.cpp
  tests/cpp_unit_tests/test_optimizer.hpp
  tests/cpp_unit_tests/test_shunt.cpp
  tests/cpp_unit_tests/test_source.cpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/cpp_unit_tests/test_three_winding_transformer.cpp
  tests/cpp_unit_tests/test_y_bus.cpp
Labels: feature

#584 [FEATURE] migrate to miniforge
  .github/conda_pgm_env.yml
  .github/workflows/main.yml
  README.md
  docs/advanced_documentation/build-guide.md
Labels: improvement

#592 fix performance regression
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
Labels: bug

#590 automatic tap changer outer loop multiple transformer test
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#591 [Feature] elaborate null in JSON and nil in msgpack schemas
  docs/user_manual/serialization.md
Labels: documentation

#589 add retry logic when tap optimizer diverges
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
Labels: improvement

#588 Feature/line drop compensation tests
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: improvement

#596 Feature/default build
  .github/workflows/main.yml
  CMakeLists.txt
  CMakePresets.json
  build.sh
  docs/advanced_documentation/build-guide.md
  power_grid_model_c/power_grid_model/CMakeLists.txt
Labels: improvement

#600 [Feature] migrate gcc-13
  .github/workflows/main.yml
Labels: improvement

#599 Feature/cleaner cpp api integration
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model_c/src/model.cpp
  tests/benchmark_cpp/benchmark.cpp
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_integration_tests/test_main_model_sc.cpp
  tests/cpp_integration_tests/test_main_model_se.cpp
  tests/cpp_validation_tests/test_validation.cpp
Labels: improvement

#597 [Feature] Automatic Tap Changer C API
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/basics.h
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/options.h
  power_grid_model_c/power_grid_model_c/src/model.cpp
  power_grid_model_c/power_grid_model_c/src/options.cpp
  power_grid_model_c/power_grid_model_c/src/options.hpp
  src/power_grid_model/core/error_handling.py
  src/power_grid_model/errors.py
  tests/c_api_tests/test_c_api_model.cpp
  tests/cpp_unit_tests/test_optimizer.cpp
Labels: feature

#604 [Feature] enable Python API for auto tap changer (experimental)
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  src/power_grid_model/core/error_handling.py
  src/power_grid_model/core/options.py
  src/power_grid_model/core/power_grid_core.py
  src/power_grid_model/core/power_grid_model.py
  src/power_grid_model/enum.py
  tests/unit/test_error_handling.py
Labels: feature

#605 [Feature] tap regulator output data declaration
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_tap_regulator.hpp
Labels: feature

#607 Feature/tap regulator output
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_tap_regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#598 feature/update main model for automatic tap changer
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_tap_regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/base_optimizer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_load_gen.cpp
  tests/cpp_unit_tests/test_main_core_output.cpp
  tests/cpp_unit_tests/test_optimizer.cpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#608 Feature/auto tap validation test
  tests/cpp_validation_tests/test_validation.cpp
  tests/data/power_flow/pgm-automatic-tap/input.json
  tests/data/power_flow/pgm-automatic-tap/input.json.license
  tests/data/power_flow/pgm-automatic-tap/params.json
  tests/data/power_flow/pgm-automatic-tap/params.json.license
  tests/data/power_flow/pgm-automatic-tap/sym_output.json.license
  tests/data/power_flow/pgm-automatic-tap/sym_output_batch.json
  tests/data/power_flow/pgm-automatic-tap/sym_output_batch.json.license
  tests/data/power_flow/pgm-automatic-tap/update_batch.json
  tests/data/power_flow/pgm-automatic-tap/update_batch.json.license
  tests/unit/test_0Z_model_validation.py
Labels: improvement

#611 [Feature] support auto tap when node ids do start at 0
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap/sym_output_batch.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap/sym_output_batch.json.license
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap/update_batch.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap/update_batch.json.license
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/sym_output.json.license
Labels: feature

#612 [Feature] - set line drop compensation to 0 by default
  power_grid_model_c/power_grid_model/include/power_grid_model/common/three_phase_tensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_tap_regulator.hpp
  tests/cpp_unit_tests/test_transformer_tap_regulator.cpp
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/sym_output_batch.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/sym_output_batch.json.license
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/update_batch.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-any-valid-tap/update_batch.json.license
  tests/data/power_flow/automatic-tap-regulator/single-trafo-max-voltage-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-max-voltage-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/single-trafo-max-voltage-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-max-voltage-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/single-trafo-max-voltage-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-max-voltage-tap/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/single-trafo-min-voltage-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-min-voltage-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/single-trafo-min-voltage-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-min-voltage-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/single-trafo-min-voltage-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/single-trafo-min-voltage-tap/sym_output.json.license
Labels: feature

#614 feature/maximum iteration per rank to prevent infinite loop
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  src/power_grid_model/core/error_handling.py
  src/power_grid_model/errors.py
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature
