Repository PowerGridModel/power-grid-model, pull requests merged in 2024-10, with the labels that each got.

#757 add component attribute filter options to init
  src/power_grid_model/__init__.py
Labels: improvement

#699 Feature/columnar dataset python extension
  .github/workflows/check-code-quality.yml
  .pre-commit-config.yaml
  src/power_grid_model/_utils.py
  src/power_grid_model/core/buffer_handling.py
  src/power_grid_model/core/power_grid_core.py
  src/power_grid_model/core/power_grid_dataset.py
  src/power_grid_model/core/power_grid_meta.py
  src/power_grid_model/data_types.py
  src/power_grid_model/utils.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/utils.py
  src/power_grid_model/validation/validation.py
  tests/unit/test_internal_utils.py
  tests/unit/test_serialization.py
  tests/unit/utils.py
Labels: feature

#758 Feature / deserialization data filter relevant logic in place
  docs/api_reference/python-api-reference.md
  docs/user_manual/serialization.md
  src/power_grid_model/__init__.py
  src/power_grid_model/_utils.py
  src/power_grid_model/core/power_grid_dataset.py
  src/power_grid_model/core/serialization.py
  src/power_grid_model/enum.py
  src/power_grid_model/typing.py
  tests/unit/test_internal_utils.py
  tests/unit/test_serialization.py
  tests/unit/validation/test_batch_validation.py
  tests/unit/validation/test_input_validation.py
Labels: feature

#768 Bug/Fix columnar batch validation function
  src/power_grid_model/validation/validation.py
  tests/unit/validation/test_batch_validation.py
Labels: bug, improvement

#767 Feature/Add utils to Cpp wrapper
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/basics.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/utils.hpp
  tests/cpp_validation_tests/test_validation.cpp
Labels: feature

#769 Repro case for buffer alignment
  build.sh
  power_grid_model_c/power_grid_model_c/src/handle.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/meta_data.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/utils.hpp
  tests/cpp_validation_tests/test_validation.cpp
  tests/native_api_tests/CMakeLists.txt
  tests/native_api_tests/test_api_buffer.cpp
  tests/native_api_tests/test_api_utils.cpp
Labels: improvement

#775 Fix Nightly Clang-Tidy run
  .github/workflows/clang-tidy.yml
  tests/cpp_unit_tests/test_generic_branch.cpp
Labels: improvement

#777 auto tap validation test for meshed grid with transformers
  pyproject.toml
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-any/input.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-any/input.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-any/params.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-any/params.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-any/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-any/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-fast-any/input.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-fast-any/input.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-fast-any/params.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-fast-any/params.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-fast-any/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-fast-any/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-max/input.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-max/input.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-max/params.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-max/params.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-max/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-max/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-min/input.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-min/input.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-min/params.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-min/params.json.license
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-min/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-min/sym_output.json.license
Labels: improvement

#779 Bug/Convert to/form row/col util function
  src/power_grid_model/_utils.py
  tests/unit/test_internal_utils.py
  tests/unit/validation/test_batch_validation.py
Labels: bug

#780 Remove sphinx workaround
  pyproject.toml
Labels: bug

#778 Improvement/Integration tests for columnar data
  tests/unit/test_power_grid_model.py
Labels: improvement

#781 [Feature] columnar data Python API docs
  .gitignore
  docs/api_reference/power-grid-model-c-api-reference.rst
  docs/api_reference/python-api-reference.md
  src/power_grid_model/core/power_grid_meta.py
  src/power_grid_model/core/power_grid_model.py
  src/power_grid_model/data_types.py
  src/power_grid_model/enum.py
  src/power_grid_model/errors.py
  src/power_grid_model/typing.py
  src/power_grid_model/utils.py
Labels: documentation

#792 BugFix / Capital enums made lower case
  src/power_grid_model/core/power_grid_dataset.py
  src/power_grid_model/enum.py
  tests/unit/test_internal_utils.py
  tests/unit/test_power_grid_model.py
  tests/unit/test_serialization.py
  tests/unit/validation/test_batch_validation.py
  tests/unit/validation/test_input_validation.py
Labels: bug

#785 [Feature] - columnar data examples
  docs/examples/Asymmetric Calculation Example.ipynb
  docs/examples/Make Test Dataset.ipynb
  docs/examples/Power Flow Example.ipynb
  docs/examples/Serialization Example.ipynb
  docs/examples/Short Circuit Example.ipynb
  docs/examples/State Estimation Example.ipynb
  docs/examples/Transformer Examples.ipynb
  docs/examples/Validation Examples.ipynb
  src/power_grid_model/validation/errors.py
  tests/unit/validation/test_errors.py
  tests/unit/validation/test_rules.py
Labels: documentation

#799 improve C API documentation
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/buffer.h
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/dataset.h
Labels: documentation

#795 Bug / Fix error handling tests in API tests
  tests/native_api_tests/test_api_meta_data.cpp
  tests/native_api_tests/test_api_model.cpp
  tests/native_api_tests/test_api_serialization.cpp
Labels: bug

#801 Feature - columnar performance docs
  docs/user_manual/calculations.md
  docs/user_manual/performance-guide.md
Labels: documentation

#805 UB update unknown id repro case
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/three_phase_tensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  tests/cpp_integration_tests/test_main_model.cpp
  tests/cpp_integration_tests/test_main_model_static.cpp
  tests/native_api_tests/test_api_model.cpp
  tests/unit/test_power_grid_model.py
Labels: bug

#810 BUG / Memory access violation in buffer span of update data
  tests/native_api_tests/test_api_model.cpp
Labels: bug

#793 Feature / Update Python validation to support optional `id` in update data
  src/power_grid_model/_utils.py
  src/power_grid_model/validation/errors.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/validation.py
  tests/unit/validation/test_batch_validation.py
  tests/unit/validation/test_validation_functions.py
Labels: feature

#807 Feature/improve docs
  docs/advanced_documentation/build-guide.md
  docs/advanced_documentation/c-api.md
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/model.h
  src/power_grid_model/core/power_grid_model.py
Labels: documentation
