Repository PowerGridModel/power-grid-model, pull requests merged in 2025-03, with the labels that each got.

#909 Step-up transformer tap changer support: patch new transformer ranking error message
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
Labels: bug, feature

#892 Step-up transformer tap changer support: unit test for new control logic
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#895 Improve memory footprint of columnar deserialization using relevant filter
  .vscode/extensions.json
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/deserializer.hpp
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/dataset.h
  power_grid_model_c/power_grid_model_c/src/dataset.cpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/dataset.hpp
  src/power_grid_model/_core/power_grid_core.py
  src/power_grid_model/_core/power_grid_dataset.py
  tests/cpp_unit_tests/test_deserializer.cpp
  tests/native_api_tests/test_api_serialization.cpp
Labels: improvement

#917 Refactor to DecomposedComplexRandVar
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/current_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/power_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/measured_values.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_se_solver.hpp
  tests/cpp_unit_tests/test_current_sensor.cpp
  tests/cpp_unit_tests/test_math_solver_se.hpp
  tests/cpp_unit_tests/test_measured_values.cpp
  tests/cpp_unit_tests/test_observability.cpp
  tests/cpp_unit_tests/test_power_sensor.cpp
Labels: feature

#919 Cleanup import statements: update expositions and document exposed symbols
  docs/api_reference/python-api-reference.md
  src/power_grid_model/validation/__init__.py
  src/power_grid_model/validation/_rules.py
  src/power_grid_model/validation/_validation.py
  src/power_grid_model/validation/assertions.py
  src/power_grid_model/validation/utils.py
  tests/unit/validation/test_rules.py
  tests/unit/validation/test_validation_functions.py
Labels: feature

#916 Use math solver dispatch to separate math solver from main model
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/math_state.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_current_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/linear_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/math_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/math_solver_dispatch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/short_circuit_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  power_grid_model_c/power_grid_model_c/CMakeLists.txt
  power_grid_model_c/power_grid_model_c/src/math_solver.cpp
  power_grid_model_c/power_grid_model_c/src/math_solver.hpp
  power_grid_model_c/power_grid_model_c/src/model.cpp
  setup.py
Labels: feature, improvement

#923 Automatic tap changer step up transformer support: Python validation
  src/power_grid_model/validation/_rules.py
  src/power_grid_model/validation/_validation.py
  src/power_grid_model/validation/errors.py
  tests/unit/validation/test_input_validation.py
  tests/unit/validation/test_rules.py
  tests/unit/validation/test_validation_functions.py
Labels: feature

#924 bump macos min version
  setup.py
Labels: dependencies

#921 Drop manylinux_2_24 and MacOS < 13.3
  pyproject.toml
  setup.py
Labels: dependencies

#922 Support for clang tidy 19
  .clang-tidy
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/deserializer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/serializer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/three_phase_tensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/timer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/base.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch3.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/component.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/current_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/load_gen.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/node.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/power_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/shunt.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/source.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/three_winding_transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_tap_regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/voltage_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/observability.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/topology.hpp
  power_grid_model_c/power_grid_model_c/src/handle.cpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/dataset.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/handle.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_container.cpp
  tests/cpp_unit_tests/test_current_sensor.cpp
  tests/cpp_unit_tests/test_fault.cpp
  tests/cpp_unit_tests/test_index_mapping.cpp
  tests/cpp_unit_tests/test_line.cpp
  tests/cpp_unit_tests/test_link.cpp
  tests/cpp_unit_tests/test_math_solver_common.hpp
  tests/cpp_unit_tests/test_math_solver_sc.cpp
  tests/cpp_unit_tests/test_math_solver_se.hpp
  tests/cpp_unit_tests/test_measured_values.cpp
  tests/cpp_unit_tests/test_observability.cpp
  tests/cpp_unit_tests/test_optimizer.hpp
  tests/cpp_unit_tests/test_power_sensor.cpp
  tests/cpp_unit_tests/test_shunt.cpp
  tests/cpp_unit_tests/test_sparse_lu_solver.cpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/cpp_unit_tests/test_three_winding_transformer.cpp
  tests/cpp_unit_tests/test_topology.cpp
  tests/cpp_unit_tests/test_voltage_sensor.cpp
  tests/cpp_validation_tests/test_validation.cpp
  tests/native_api_tests/test_api_model.cpp
Labels: improvement

#925 Try to fix macOS version bump
  .readthedocs.yaml
  docs/advanced_documentation/build-guide.md
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  pyproject.toml
  setup.py
  src/power_grid_model/validation/_rules.py
Labels: improvement

#890 Add LU solver documentation
  docs/advanced_documentation/build-guide.md
  docs/advanced_documentation/python-wrapper-design.md
  docs/algorithms/lu-solver.md
  docs/conf.py
  docs/index.md
Labels: documentation

#928 Clang tidy 19 support (bis)
  .clang-tidy
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/deserializer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/serializer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/three_phase_tensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/timer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/base.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch3.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/component.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/current_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/load_gen.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/node.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/power_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/shunt.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/source.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/three_winding_transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_tap_regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/voltage_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/observability.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/topology.hpp
  power_grid_model_c/power_grid_model_c/src/handle.cpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/dataset.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/handle.hpp
  tests/benchmark_cpp/benchmark.cpp
  tests/benchmark_cpp/fictional_grid_generator.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_container.cpp
  tests/cpp_unit_tests/test_current_sensor.cpp
  tests/cpp_unit_tests/test_fault.cpp
  tests/cpp_unit_tests/test_index_mapping.cpp
  tests/cpp_unit_tests/test_line.cpp
  tests/cpp_unit_tests/test_link.cpp
  tests/cpp_unit_tests/test_math_solver_common.hpp
  tests/cpp_unit_tests/test_math_solver_sc.cpp
  tests/cpp_unit_tests/test_math_solver_se.hpp
  tests/cpp_unit_tests/test_measured_values.cpp
  tests/cpp_unit_tests/test_observability.cpp
  tests/cpp_unit_tests/test_optimizer.hpp
  tests/cpp_unit_tests/test_power_sensor.cpp
  tests/cpp_unit_tests/test_shunt.cpp
  tests/cpp_unit_tests/test_sparse_lu_solver.cpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/cpp_unit_tests/test_three_winding_transformer.cpp
  tests/cpp_unit_tests/test_topology.cpp
  tests/cpp_unit_tests/test_voltage_sensor.cpp
  tests/cpp_validation_tests/test_validation.cpp
  tests/native_api_tests/test_api_model.cpp
Labels: improvement

#929 Unreachable regulators condition is moved
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-any/input.json
  tests/data/power_flow/automatic-tap-regulator/pgm-automatic-tap-any/sym_output_batch.json
  tests/unit/test_error_handling.py
Labels: bug

#908 Workflow setup
  .github/workflows/build-test-release.yml
  .github/workflows/check-blocking-labels.yml
  .github/workflows/check-code-quality.yml
  .github/workflows/ci.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/reuse-compliance.yml
  README.md
Labels: feature

#937 Fix the release/pypi secrets
  .github/workflows/build-test-release.yml
  .github/workflows/ci.yml
Labels: bug
