Repository PowerGridModel/power-grid-model, pull requests merged in 2025-07, with the labels that each got.

#1028 Current sensor: NRSE local angle implementation
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_se_solver.hpp
  tests/cpp_unit_tests/test_math_solver_common.hpp
  tests/cpp_unit_tests/test_math_solver_se.hpp
  tests/data/state_estimation/current-sensor/local-current-sensor/params.json
Labels: feature

#1033 Clang tidy: fix configuration + resolve newly introduced issues
  .clang-tidy
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/meta_data.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/deserializer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/iterator_facade.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/three_phase_tensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/timer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/asym_line.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/current_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/line_utils.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/observability.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  power_grid_model_c/power_grid_model_c/src/buffer.cpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/handle.hpp
  power_grid_model_c/power_grid_model_cpp/include/power_grid_model_cpp/serialization.hpp
  tests/cpp_unit_tests/test_asym_line.cpp
  tests/cpp_unit_tests/test_common.cpp
  tests/cpp_unit_tests/test_current_sensor.cpp
  tests/cpp_unit_tests/test_fault.cpp
  tests/cpp_unit_tests/test_grouped_index_vector.cpp
  tests/cpp_unit_tests/test_index_mapping.cpp
  tests/cpp_unit_tests/test_line.cpp
  tests/cpp_unit_tests/test_link.cpp
  tests/cpp_unit_tests/test_measured_values.cpp
  tests/cpp_unit_tests/test_node.cpp
  tests/cpp_unit_tests/test_shunt.cpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/cpp_unit_tests/test_three_phase_tensor.cpp
  tests/cpp_unit_tests/test_three_winding_transformer.cpp
  tests/cpp_unit_tests/test_transformer_tap_regulator.cpp
  tests/cpp_unit_tests/test_voltage_sensor.cpp
  tests/cpp_unit_tests/test_y_bus.cpp
  tests/native_api_tests/test_api_model.cpp
  tests/native_api_tests/test_api_serialization.cpp
Labels: feature

#1040 Current sensor: Remove experimental feature flag - local angle NRSE
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  tests/data/state_estimation/current-sensor/local-current-sensor/params.json
  tests/native_api_tests/test_api_model.cpp
Labels: feature

#1038 Data validator: fix infinite p/q_sigma validation
  src/power_grid_model/validation/_validation.py
  tests/unit/validation/test_input_validation.py
  tests/unit/validation/test_validation_functions.py
Labels: bug

#1037 Use of enumerations: Clean remaining ComponentType and DatasetType in data validator
  src/power_grid_model/utils.py
  src/power_grid_model/validation/_rules.py
  src/power_grid_model/validation/_validation.py
  src/power_grid_model/validation/assertions.py
  src/power_grid_model/validation/errors.py
  src/power_grid_model/validation/utils.py
  tests/unit/validation/test_batch_validation.py
  tests/unit/validation/test_errors.py
  tests/unit/validation/test_input_validation.py
  tests/unit/validation/test_rules.py
  tests/unit/validation/test_utils.py
  tests/unit/validation/test_validation_functions.py
Labels: improvement

#1042 Use of enumerations: Clean remaining enums in other places
  src/power_grid_model/data_types.py
  tests/unit/test_0Z_model_validation.py
  tests/unit/test_dataset.py
  tests/unit/test_error_handling.py
  tests/unit/test_internal_utils.py
  tests/unit/test_serialization.py
  tests/unit/test_utils.py
Labels: improvement

#1049 Validation cases: split validation case `fail` into `xfail` and `raises`
  docs/examples/Make Test Dataset.ipynb
  tests/cpp_validation_tests/test_validation.cpp
  tests/data/power_flow/automatic-tap-regulator/auto-tap-changer-meshed-any-max-iter/params.json
  tests/data/power_flow/non-existent-id-update-batch/params.json
  tests/data/state_estimation/current-sensor/global-current-sensor/params.json
  tests/data/state_estimation/ill-conditioned-system/leaf-without-power-sensor-meshed/params.json
  tests/data/state_estimation/not-independent-sensor/not-independent-sensor-with-phasor-sensors/params.json
  tests/data/state_estimation/not-independent-sensor/not-independent-sensor/params.json
  tests/unit/test_0Z_model_validation.py
  tests/unit/utils.py
Labels: feature

#1018 Cleanup main model: Job dispatch into separate file
  power_grid_model_c/power_grid_model/include/power_grid_model/job_dispatch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/calculation_info.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
Labels: improvement

#1043 Internal improvements: more constexpr + unit tests
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/three_phase_tensor.hpp
  tests/cpp_unit_tests/test_exceptions.cpp
  tests/cpp_unit_tests/test_three_phase_tensor.cpp
Labels: improvement

#1054 CI: bump compilers
  .github/workflows/build-test-release.yml
  docs/advanced_documentation/build-guide.md
Labels: documentation, dependencies

#1044 Full observability check: meshed validation cases
  docs/user_manual/calculations.md
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/observability.hpp
  tests/cpp_unit_tests/test_exceptions.cpp
  tests/data/state_estimation/meshed-network-observability/01-observable-with-branch-measurement/input.json
  tests/data/state_estimation/meshed-network-observability/01-observable-with-branch-measurement/input.json.license
  tests/data/state_estimation/meshed-network-observability/01-observable-with-branch-measurement/params.json
  tests/data/state_estimation/meshed-network-observability/01-observable-with-branch-measurement/params.json.license
  tests/data/state_estimation/meshed-network-observability/01-observable-with-branch-measurement/sym_output.json
  tests/data/state_estimation/meshed-network-observability/01-observable-with-branch-measurement/sym_output.json.license
  tests/data/state_estimation/meshed-network-observability/02-unobservable-with-branch-measurement/input.json
  tests/data/state_estimation/meshed-network-observability/02-unobservable-with-branch-measurement/input.json.license
  tests/data/state_estimation/meshed-network-observability/02-unobservable-with-branch-measurement/params.json
  tests/data/state_estimation/meshed-network-observability/02-unobservable-with-branch-measurement/params.json.license
  tests/data/state_estimation/meshed-network-observability/02-unobservable-with-branch-measurement/sym_output.json
  tests/data/state_estimation/meshed-network-observability/02-unobservable-with-branch-measurement/sym_output.json.license
  tests/data/state_estimation/meshed-network-observability/03-observable-without-branch-measurement/input.json
  tests/data/state_estimation/meshed-network-observability/03-observable-without-branch-measurement/input.json.license
  tests/data/state_estimation/meshed-network-observability/03-observable-without-branch-measurement/params.json
  tests/data/state_estimation/meshed-network-observability/03-observable-without-branch-measurement/params.json.license
  tests/data/state_estimation/meshed-network-observability/03-observable-without-branch-measurement/sym_output.json
  tests/data/state_estimation/meshed-network-observability/03-observable-without-branch-measurement/sym_output.json.license
  tests/data/state_estimation/meshed-network-observability/04-observable-without-branch-measurement/input.json
  tests/data/state_estimation/meshed-network-observability/04-observable-without-branch-measurement/input.json.license
  tests/data/state_estimation/meshed-network-observability/04-observable-without-branch-measurement/params.json
  tests/data/state_estimation/meshed-network-observability/04-observable-without-branch-measurement/params.json.license
  tests/data/state_estimation/meshed-network-observability/04-observable-without-branch-measurement/sym_output.json
  tests/data/state_estimation/meshed-network-observability/04-observable-without-branch-measurement/sym_output.json.license
  tests/data/state_estimation/meshed-network-observability/README.md
  tests/data/state_estimation/meshed-network-observability/test_network_diagrams.svg
  tests/data/state_estimation/meshed-network-observability/test_network_diagrams.svg.license
Labels: feature

#1051 Validation cases: same behavior in C++ as Python for test cases with exceptions
  src/power_grid_model/_core/error_handling.py
  src/power_grid_model/_core/errors.py
  tests/cpp_validation_tests/test_validation.cpp
  tests/data/power_flow/non-existent-id-update-batch/params.json
  tests/unit/utils.py
Labels: improvement
