Repository PowerGridModel/power-grid-model, pull requests merged in 2025-10, with the labels that each got.

#1143 Dependencies: Drop NumPy 1.x support
  pyproject.toml
Labels: dependencies

#1147 Feature: add community.md to readthedocs
  .readthedocs.yaml
  docs/index.md
Labels: feature

#1140 Performance: Using swapping in places explicit copying could been avoided
  power_grid_model_c/power_grid_model/include/power_grid_model/index_mapping.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  tests/cpp_unit_tests/test_y_bus.cpp
Labels: improvement
