Repository PowerGridModel/power-grid-model, pull requests merged in 2025-08, with the labels that each got.

#1055 Performance: fix memory creep + false sharing in calculation info
  power_grid_model_c/power_grid_model/include/power_grid_model/job_dispatch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/calculation_info.hpp
Labels: bug

#1011 Transformer: support periodic clock input
  docs/examples/Transformer Examples.ipynb
  docs/user_manual/components.md
  power_grid_model_c/power_grid_model/include/power_grid_model/common/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/three_winding_transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_utils.hpp
  src/power_grid_model/validation/_validation.py
  tests/cpp_unit_tests/test_common.cpp
  tests/cpp_unit_tests/test_three_winding_transformer.cpp
  tests/cpp_unit_tests/test_transformer.cpp
  tests/unit/validation/test_input_validation.py
Labels: feature

#1030 NRSE current sensor: Global angle current sensor
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_se_solver.hpp
  tests/cpp_unit_tests/test_math_solver_se.hpp
  tests/data/state_estimation/current-sensor/global-current-sensor/params.json
Labels: feature

#1057 Clean-up main model: adopt common tensor naming strategy
  power_grid_model_c/power_grid_model/include/power_grid_model/common/common.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/three_phase_tensor.hpp
Labels: improvement

#1019 use scikit-build-core as build backend
  .github/actions/enable-msvc/action.yml
  .github/conda_pgm_env.yml
  .github/workflows/build-test-release.yml
  MANIFEST.in
  cmake/pgm_version.cmake
  docs/advanced_documentation/build-guide.md
  pyproject.toml
  setup.py
  src/power_grid_model/_core/power_grid_core.py
  src/power_grid_model/_core/power_grid_model_c/__init__.py
  src/power_grid_model/_core/power_grid_model_c/get_pgm_dll_path.py
Labels: improvement

#1065 Linting and Formatting: RUF, UP and RSE checks
  .pre-commit-config.yaml
  code_generation/code_gen.py
  code_generation/templates/src/power_grid_model/_core/dataset_class_maps.py.jinja
  pyproject.toml
  src/power_grid_model/__init__.py
  src/power_grid_model/_core/data_handling.py
  src/power_grid_model/_core/dataset_definitions.py
  src/power_grid_model/_core/options.py
  src/power_grid_model/_core/power_grid_core.py
  src/power_grid_model/_core/power_grid_dataset.py
  src/power_grid_model/_core/power_grid_model.py
  src/power_grid_model/_core/utils.py
  src/power_grid_model/data_types.py
  src/power_grid_model/typing.py
  src/power_grid_model/validation/__init__.py
  src/power_grid_model/validation/_rules.py
  src/power_grid_model/validation/errors.py
  src/power_grid_model/validation/utils.py
  tests/unit/test_0Z_model_validation.py
  tests/unit/test_data_handling.py
  tests/unit/test_serialization.py
  tests/unit/validation/test_input_validation.py
Labels: feature

#1066 Clean-up main model: migrate job dispatch out of main model impl
  power_grid_model_c/power_grid_model/include/power_grid_model/job_adapter.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
Labels: improvement

#1072 Clean-up main model: index-less single-scenario calculation
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/job_adapter.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/job_interface.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  tests/cpp_unit_tests/test_container.cpp
  tests/cpp_unit_tests/test_dataset.cpp
  tests/cpp_unit_tests/test_main_core_output.cpp
Labels: improvement

#1078 Clean-up main model: move prepare calculation logic
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/calculation_input_preparation.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
Labels: improvement

#1082 Internal benchmark: fix timer
  power_grid_model_c/power_grid_model/include/power_grid_model/job_dispatch.hpp
Labels: improvement

#1091 Clean-up main model: Rename job dispatch-related classes
  power_grid_model_c/power_grid_model/include/power_grid_model/job_adapter.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/job_dispatch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/job_interface.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
Labels: improvement

#1094 Clean-up main model: migrate reset calculation info to job dispatch
  power_grid_model_c/power_grid_model/include/power_grid_model/job_adapter.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/job_dispatch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/job_interface.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  tests/benchmark_cpp/benchmark.cpp
  tests/cpp_unit_tests/test_job_dispatch.cpp
Labels: improvement

#1092 Clean-up main model: move topology related construction
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container_fwd.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/container_queries.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/state.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/state_queries.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/topology.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/optimizer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_container.cpp
  tests/cpp_unit_tests/test_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: improvement

#1104 Compiler support: enable C++23 in PGM core compilation
  CMakeLists.txt
  docs/advanced_documentation/build-guide.md
  power_grid_model_c/power_grid_model/include/power_grid_model/common/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  tests/cpp_unit_tests/test_y_bus.cpp
Labels: improvement
