Repository PowerGridModel/power-grid-model, pull requests merged in 2025-02, with the labels that each got.

#888 Update citations
  CITATION.cff
  README.md
Labels: documentation

#891 Generate model validation grid graphs with tikz
  docs/conf.py
  docs/images/validation/asym_gen.svg
  docs/images/validation/asym_gen.svg.license
  docs/images/validation/asym_load.svg
  docs/images/validation/asym_load.svg.license
  docs/images/validation/basic_node.svg
  docs/images/validation/basic_node.svg.license
  docs/images/validation/line.svg
  docs/images/validation/line.svg.license
  docs/images/validation/node.svg
  docs/images/validation/node.svg.license
  docs/images/validation/sc_validation_case.svg
  docs/images/validation/sc_validation_case.svg.license
  docs/images/validation/shunt.svg
  docs/images/validation/shunt.svg.license
  docs/images/validation/source.svg
  docs/images/validation/source.svg.license
  docs/images/validation/sym_gen.svg
  docs/images/validation/sym_gen.svg.license
  docs/images/validation/sym_load.svg
  docs/images/validation/sym_load.svg.license
  docs/images/validation/transformer.svg
  docs/images/validation/transformer.svg.license
  docs/index.md
  docs/user_manual/calculations.md
  docs/user_manual/model-validation.md
  pyproject.toml
Labels: documentation

#906 Drop python 3.10: fix documentation
  docs/advanced_documentation/build-guide.md
Labels: documentation

#894 Step-up transformer tap changer support: binary search control logic
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#893 Step-up transformer tap changer support: linear search control logic
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: feature

#897 Refactor for easier testing
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: improvement

#910 Fix nightly
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: improvement

#903 Current sensor component functionality
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/current_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/power_sensor.hpp
  power_grid_model_c/power_grid_model_c/src/handle.hpp
  tests/cpp_unit_tests/test_current_sensor.cpp
Labels: feature

#907 Bugfix: rule in none missing yield false positives
  docs/user_manual/components.md
  src/power_grid_model/validation/errors.py
  src/power_grid_model/validation/rules.py
  src/power_grid_model/validation/validation.py
  tests/unit/validation/test_rules.py
  tests/unit/validation/test_validation_functions.py
Labels: bug

#911 Update transformer regulator doc w.r.t. control side
  docs/user_manual/components.md
Labels: documentation

#896 Measurement statistics module
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/current_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/power_sensor.hpp
  power_grid_model_c/power_grid_model_c/src/handle.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_current_sensor.cpp
  tests/cpp_unit_tests/test_statistics.cpp
Labels: feature
