Repository PowerGridModel/power-grid-model, pull requests merged in 2025-01, with the labels that each got.

#866 Fix quality issue
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/short_circuit_solver.hpp
Labels: improvement

#860 Resolve difference between input and update
  power_grid_model_c/power_grid_model/include/power_grid_model/component/power_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/voltage_sensor.hpp
  tests/cpp_unit_tests/test_power_sensor.cpp
  tests/cpp_unit_tests/test_voltage_sensor.cpp
Labels: bug

#871 Bugfix for quadratic blow-up of batch validation errors
  src/power_grid_model/validation/validation.py
  tests/unit/validation/test_batch_validation.py
Labels: bug

#873 disable cmake policy that removes FindBoost.cmake
  CMakeLists.txt
Labels: dependencies

#876 fix clang-tidy
  tests/cpp_unit_tests/test_current_sensor.cpp
  tests/cpp_unit_tests/test_power_sensor.cpp
  tests/cpp_unit_tests/test_voltage_sensor.cpp
Labels: improvement

#868 Step-up transformer tap changer support: additional tests
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-any-valid-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-any-valid-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-any-valid-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-any-valid-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-any-valid-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-any-valid-tap/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-fast-any-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-fast-any-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-fast-any-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-fast-any-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-fast-any-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-fast-any-tap/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-max-voltage-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-max-voltage-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-max-voltage-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-max-voltage-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-max-voltage-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-max-voltage-tap/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-min-voltage-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-min-voltage-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-min-voltage-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-min-voltage-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-min-voltage-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/step-up-transformer-min-voltage-tap/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-any-valid-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-any-valid-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-any-valid-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-any-valid-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-any-valid-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-any-valid-tap/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-fast-any-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-fast-any-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-fast-any-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-fast-any-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-fast-any-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-fast-any-tap/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-max-voltage-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-max-voltage-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-max-voltage-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-max-voltage-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-max-voltage-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-max-voltage-tap/sym_output.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-min-voltage-tap/input.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-min-voltage-tap/input.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-min-voltage-tap/params.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-min-voltage-tap/params.json.license
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-min-voltage-tap/sym_output.json
  tests/data/power_flow/automatic-tap-regulator/trafo-control-side-HV-min-voltage-tap/sym_output.json.license
Labels: feature

#881 Fix a bug on relevant filter
  src/power_grid_model/_core/power_grid_dataset.py
  tests/unit/test_serialization.py
Labels: bug

#879 Drop python 3.10
  pyproject.toml
Labels: dependencies

#884 improve docs on batch error
  src/power_grid_model/_core/power_grid_model.py
Labels: documentation
