Repository PowerGridModel/power-grid-model, pull requests merged in 2025-09, with the labels that each got.

#1105 Clean-up main model: move y_bus related construction
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/math_state.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/y_bus.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
Labels: improvement

#1111 Clean-up main model: fix windows clang-tidy
  power_grid_model_c/power_grid_model/include/power_grid_model/job_interface.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/topology.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/y_bus.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  tests/benchmark_cpp/benchmark.cpp
  tests/benchmark_cpp/fictional_grid_generator.hpp
  tests/cpp_unit_tests/test_dataset.cpp
  tests/cpp_unit_tests/test_exceptions.cpp
Labels: improvement

#1113 CI: update ci build tools
  .github/workflows/build-test-release.yml
  .github/workflows/check-code-quality.yml
  .readthedocs.yaml
Labels: dependencies, github_actions

#1114 Clean-up main model: clang tidy bis
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/y_bus.hpp
  tests/cpp_unit_tests/test_dataset.cpp
Labels: improvement

#1121 Fix nightly: RUF043
  pyproject.toml
  tests/unit/test_buffer_handling.py
  tests/unit/test_data_handling.py
  tests/unit/test_dataset.py
  tests/unit/test_internal_utils.py
  tests/unit/test_serialization.py
  tests/unit/test_utils.py
  tests/unit/validation/test_rules.py
  tests/unit/validation/test_validation_functions.py
Labels: improvement

#1128 Sonar cloud issues: std::to_underlying + status_to_int
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/deserializer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/serialization/serializer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/three_phase_tensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/base.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/branch3.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/fault.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/load_gen.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/shunt.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/source.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/three_winding_transformer.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer_tap_regulator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/topology.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_asym_line.cpp
  tests/cpp_unit_tests/test_fault.cpp
  tests/cpp_unit_tests/test_line.cpp
  tests/cpp_unit_tests/test_link.cpp
  tests/cpp_unit_tests/test_shunt.cpp
  tests/cpp_unit_tests/test_source.cpp
  tests/cpp_unit_tests/test_three_winding_transformer.cpp
  tests/cpp_unit_tests/test_transformer.cpp
  tests/cpp_unit_tests/test_transformer_tap_regulator.cpp
Labels: improvement

#1118 Sparse matrix error: validation cases
  tests/data/state_estimation/ill-conditioned-by-line-meshed/input.json
  tests/data/state_estimation/ill-conditioned-by-line-meshed/input.json.license
  tests/data/state_estimation/ill-conditioned-by-line-meshed/params.json
  tests/data/state_estimation/ill-conditioned-by-line-meshed/params.json.license
  tests/data/state_estimation/ill-conditioned-by-line-meshed/sym_output.json
  tests/data/state_estimation/ill-conditioned-by-line-meshed/sym_output.json.license
  tests/data/state_estimation/ill-conditioned-by-link-meshed/input.json
  tests/data/state_estimation/ill-conditioned-by-link-meshed/input.json.license
  tests/data/state_estimation/ill-conditioned-by-link-meshed/params.json
  tests/data/state_estimation/ill-conditioned-by-link-meshed/params.json.license
  tests/data/state_estimation/ill-conditioned-by-link-meshed/sym_output.json
  tests/data/state_estimation/ill-conditioned-by-link-meshed/sym_output.json.license
Labels: bug

#1109 Cleanup main model: Clean up templates and variadics
  power_grid_model_c/power_grid_model/include/power_grid_model/job_adapter.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/core_utils.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/main_model_type.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/topology.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_main_model_type.cpp
Labels: improvement

#1123 Cleanup main model: Move state queries to component queries
  power_grid_model_c/power_grid_model/include/power_grid_model/container_fwd.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/job_adapter.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/calculation_input_preparation.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/container_queries.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/state_queries.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/y_bus.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/optimizer/tap_position_optimizer.hpp
  tests/cpp_unit_tests/test_main_core_output.cpp
  tests/cpp_unit_tests/test_optimizer.hpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
Labels: improvement

#1138 Documentation: OS version in build guide
  docs/advanced_documentation/build-guide.md
Labels: documentation
