Repository PowerGridModel/power-grid-model, pull requests merged in 2025-04, with the labels that each got.

#936 Basic PGM support for creating current sensors (experimental in state estimation)
  code_generation/data/dataset_class_maps/dataset_definitions.json
  power_grid_model_c/power_grid_model/include/power_grid_model/all_components.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/calculation_parameters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/topology.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/topology.hpp
  power_grid_model_c/power_grid_model_c/include/power_grid_model_c/dataset_definitions.h
  power_grid_model_c/power_grid_model_c/src/dataset_definitions.cpp
  power_grid_model_c/power_grid_model_c/src/model.cpp
  src/power_grid_model/_core/dataset_definitions.py
  tests/data/state_estimation/basic-current-sensor/input.json
  tests/data/state_estimation/basic-current-sensor/input.json.license
  tests/data/state_estimation/basic-current-sensor/params.json
  tests/data/state_estimation/basic-current-sensor/params.json.license
  tests/data/state_estimation/basic-current-sensor/sym_output.json
  tests/data/state_estimation/basic-current-sensor/sym_output.json.license
  tests/native_api_tests/test_api_model.cpp
  tests/unit/test_0Z_model_validation.py
Labels: feature

#940 Feature/grouped idx vector std views
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/meta_gen/gen_getters.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/counting_iterator.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/iterator_facade.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/iterator_like_concepts.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/index_mapping.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/input.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/update.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/common_solver_functions.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_current_pf_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/measured_values.hpp
  tests/cpp_unit_tests/CMakeLists.txt
  tests/cpp_unit_tests/test_counting_iterator.cpp
  tests/cpp_unit_tests/test_dataset.cpp
  tests/cpp_unit_tests/test_grouped_index_vector.cpp
  tests/cpp_unit_tests/test_tap_position_optimizer.cpp
  tests/cpp_unit_tests/test_topology.cpp
  tests/cpp_unit_tests/test_y_bus.cpp
Labels: improvement

#943 Resolve AngleMeasurementType enum value name conflict
  power_grid_model_c/power_grid_model/include/power_grid_model/common/enum.hpp
  tests/cpp_unit_tests/test_current_sensor.cpp
Labels: improvement

#945 Add test workflow
  .github/workflows/test-workflow.yml
Labels: improvement

#952 change sigma to delta in tan delta equation
  docs/user_manual/components.md
Labels: documentation

#946 Adds check for test_workflow
  .github/workflows/check-code-quality.yml
Labels: improvement

#954 current sensor: math solver implementation
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/newton_raphson_se_solver.hpp
  tests/cpp_unit_tests/test_math_solver_se.hpp
  tests/cpp_validation_tests/test_validation.cpp
  tests/data/state_estimation/basic-current-sensor/params.json
Labels: feature

#955 Statistics: add scaling functionality
  power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp
  tests/cpp_unit_tests/test_statistics.cpp
Labels: improvement

#957 Local angle current measurement: fix translation to global angle current measurement
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  tests/cpp_unit_tests/test_math_solver_se.hpp
Labels: bug

#958 Current sensor: minor refactor ilse math solver
  README.md
  power_grid_model_c/power_grid_model/include/power_grid_model/common/statistics.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/math_solver/iterative_linear_se_solver.hpp
  tests/cpp_unit_tests/test_statistics.cpp
Labels: improvement

#959 reduce iterator facade complexity
  power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/dataset.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/grouped_index_vector.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/common/iterator_facade.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/container.hpp
Labels: improvement

#944 Add trusted publisher management in PyPI
  .github/workflows/build-test-release.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/publish-pypi.yml
  pyproject.toml
  set_pypi_version.py
Labels: improvement

#964 Solve some markdownlint issues
  .markdownlint.yaml
  .vscode/extensions.json
  README.md
  docs/advanced_documentation/native-data-interface.md
  docs/quickstart.md
  docs/user_manual/components.md
  docs/user_manual/data-model.md
  docs/user_manual/data-validator.md
  docs/user_manual/dataset-terminology.md
  docs/user_manual/model-validation.md
  docs/user_manual/performance-guide.md
  docs/user_manual/serialization.md
  tests/data/power_flow/generic_branch/README.md
  tests/data/power_flow/pandapower/components/asymmetric/asym_gen/README.md
  tests/data/power_flow/pandapower/components/asymmetric/asym_load/README.md
  tests/data/power_flow/pandapower/components/asymmetric/line/README.md
  tests/data/power_flow/pandapower/components/asymmetric/node/README.md
  tests/data/power_flow/pandapower/components/asymmetric/shunt/README.md
  tests/data/power_flow/pandapower/components/asymmetric/source/README.md
  tests/data/power_flow/pandapower/components/asymmetric/sym_gen/README.md
  tests/data/power_flow/pandapower/components/asymmetric/sym_load/README.md
  tests/data/power_flow/pandapower/components/asymmetric/transformer/README.md
  tests/data/power_flow/pandapower/components/symmetric/basic-node/README.md
  tests/data/power_flow/pandapower/components/symmetric/line/README.md
  tests/data/power_flow/pandapower/components/symmetric/node/README.md
  tests/data/power_flow/pandapower/components/symmetric/shunt/README.md
  tests/data/power_flow/pandapower/components/symmetric/source/README.md
  tests/data/power_flow/pandapower/components/symmetric/sym_gen/README.md
  tests/data/power_flow/pandapower/components/symmetric/sym_load/README.md
  tests/data/power_flow/pandapower/components/symmetric/three_winding_transformer/README.md
  tests/data/power_flow/pandapower/components/symmetric/transformer/README.md
  tests/data/power_flow/pandapower/networks/asymmetric/distribution-case/README.md
  tests/data/power_flow/pandapower/networks/asymmetric/transmission-case/README.md
  tests/data/power_flow/pandapower/networks/symmetric/distribution-case/README.md
  tests/data/power_flow/pandapower/networks/symmetric/transmission-case/README.md
  tests/data/state_estimation/distribution-case/README.md
  tests/data/state_estimation/transmission-case/README.md
Labels: documentation

#966 add small unit test for current sensor
  tests/unit/test_error_handling.py
Labels: improvement

#962 add current sensor + power sensor variance diff to ILSE docs
  docs/user_manual/calculations.md
  docs/user_manual/components.md
Labels: documentation

#956 Fix MacOS build for Xcode 16.3
  tests/native_api_tests/test_api_serialization.cpp
Labels: dependencies, improvement

#965 patch automatic publish PyPI
  .github/workflows/ci.yml
  .github/workflows/publish-pypi.yml
Labels: bug

#971 Add missing permissions to publish into PyPI
  .github/workflows/ci.yml
Labels: bug

#961 Fix output residuals for current sensor
  power_grid_model_c/power_grid_model/include/power_grid_model/all_components.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/component/current_sensor.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_core/output.hpp
  tests/cpp_unit_tests/test_current_sensor.cpp
  tests/data/state_estimation/basic-current-sensor/input.json
Labels: bug

#969 document high-level design PGM
  docs/advanced_documentation/high-level-design.md
  docs/conf.py
  docs/index.md
Labels: documentation

#974 Extend + fix typos current sensor docs
  docs/user_manual/calculations.md
  docs/user_manual/components.md
Labels: documentation

#973 Documentation on how to build full PGM core docs
  docs/advanced_documentation/build-guide.md
  docs/advanced_documentation/core-design.md
  docs/doxygen/Doxyfile
Labels: documentation
