Repository PowerGridModel/power-grid-model, pull requests merged in 2025-05, with the labels that each got.

#983 Add token to bump action
  .github/workflows/build-test-release.yml
Labels: feature

#953 Cleanup import statements: rearrange modules that _core imports from
  docs/api_reference/python-api-reference.md
  src/power_grid_model/_core/buffer_handling.py
  src/power_grid_model/_core/data_handling.py
  src/power_grid_model/_core/data_types.py
  src/power_grid_model/_core/enum.py
  src/power_grid_model/_core/error_handling.py
  src/power_grid_model/_core/errors.py
  src/power_grid_model/_core/power_grid_dataset.py
  src/power_grid_model/_core/power_grid_meta.py
  src/power_grid_model/_core/power_grid_model.py
  src/power_grid_model/_core/serialization.py
  src/power_grid_model/_core/typing.py
  src/power_grid_model/_core/utils.py
  src/power_grid_model/data_types.py
  src/power_grid_model/enum.py
  src/power_grid_model/errors.py
  src/power_grid_model/typing.py
  src/power_grid_model/utils.py
  src/power_grid_model/validation/_rules.py
  src/power_grid_model/validation/_validation.py
  tests/unit/deprecated/test_end_to_end.py
  tests/unit/test_0Z_model_validation.py
  tests/unit/test_data_handling.py
  tests/unit/test_internal_utils.py
  tests/unit/test_optional_ids.py
  tests/unit/test_power_grid_model.py
  tests/unit/test_serialization.py
  tests/unit/validation/test_batch_validation.py
  tests/unit/validation/test_input_validation.py
  tests/unit/validation/test_rules.py
  tests/unit/validation/test_validation_functions.py
Labels: improvement

#991 move internal utils to correct place
  src/power_grid_model/_utils.py
Labels: bug

#993 Automatic release note generation: config YAML file
  .github/release.yml
Labels: github_actions

#998 Release v1.11.x
  VERSION
  docs/index.md
  docs/user_manual/calculations.md
  docs/user_manual/components.md
  power_grid_model_c/power_grid_model/include/power_grid_model/common/exception.hpp
  power_grid_model_c/power_grid_model/include/power_grid_model/main_model_impl.hpp
  tests/native_api_tests/test_api_model.cpp
Labels: feature

#999 Documentation: resolve github rate limit by using authorized access
  .readthedocs.yaml
Labels: documentation

#1001 MacOS build still fails when using clang-17
  .github/workflows/build-test-release.yml
  pyproject.toml
  setup.py
Labels: bug

#989 PGM-IO internal import resolution: Move isnan back to internal import, step 3
  src/power_grid_model/_utils.py
Labels: bug

#1004 Current sensor: Additional tests to validation
  tests/unit/validation/test_rules.py
Labels: improvement

#996 Current sensor: validation
  docs/user_manual/calculations.md
  docs/user_manual/components.md
  src/power_grid_model/validation/_rules.py
  src/power_grid_model/validation/_validation.py
  src/power_grid_model/validation/errors.py
  tests/unit/validation/test_input_validation.py
  tests/unit/validation/test_rules.py
  tests/unit/validation/test_validation_functions.py
Labels: feature
